---
title: "251_genes.1"
author: "Christina Lauw"
date: '2022-05-19'
output: html_document
---

</style>
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 

library(tidyverse)
library(GEOquery)
library(org.Hs.eg.db)
library(limma)
library(edgeR)
library(Glimma)
library(Homo.sapiens)
library(phyloseq)
library(gtools)
library(e1071)
library(preprocessCore)
```


```{r}
Origin <- getGEO("GSE50834", GSEMatrix = TRUE)[[1]]

Pheno = pData(Origin)

Genes = fData(Origin)

Expression <- exprs(Origin)
rnames = row.names(Expression)
cnames = colnames(Expression)

Expression %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 600)) %>% 
  boxplot()

Expression_cut <- Expression %>% 
  as.data.frame() %>% 
  mutate(GSM1230946=(GSM1230903 + GSM1230904)/2) %>%
  dplyr::select(-GSM1230903) %>%
  dplyr::select(-GSM1230904) %>%
  relocate(GSM1230946,.after = GSM1230902) %>%
  dplyr::rename(GSM1230903=GSM1230946)

Expression_normalized <- normalize.quantiles(as.matrix(Expression_cut)) %>% 
  as.data.frame()

Expression_normalized %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 600)) %>% 
  boxplot()

row.names(Expression_normalized) = rnames
colnames(Expression_normalized) = cnames[-3]

row.names(Expression_cut) = rnames
colnames(Expression_cut) = cnames[-3]

Pheno_cut <- Pheno %>% filter(title != "HIV infected patient 2_2")

```


```{r}
Expression 


Ytrain = factor(Pheno$description[c(1,3:44)])

Xtrain = t(Expression)[c(1,3:44),] %>% as.data.frame()



svm_model = svm(Xtrain, Ytrain, type = "C-classification", fitted=T)

weights = t(svm_model$coefs) %*% svm_model$SV %>% as.data.frame()

sort(weights)

f_importances()
Genes

svm()

svm_model_sv <- as.data.frame(svm_model$SV)
colnames(svm_model_sv)
svm_model_sv %>% dplyr::select(ILMN_1762666, ILMN_2185884, ILMN_1790562)
t(weights %>% dplyr::select(ILMN_1762666, ILMN_2185884, ILMN_1790562, ILMN_1738075, ILMN_1806946, ILMN_2394264, ILMN_2208373, ILMN_2376723, ILMN_1714364, ILMN_1737574, ILMN_1773819, ILMN_1743396, ILMN_1668928, ILMN_1715863, ILMN_1737498, ILMN_1777915, ILMN_2157951, ILMN_1748904, ILMN_2356559, ILMN_2167416, ILMN_1666384, ILMN_1732343, ILMN_1690365, ILMN_1801931, ILMN_1653771, ILMN_1756086))


svm_model$fitted
```


```{r}
Expression_cut_t <- as.data.frame(t(Expression_cut))
Pheno_cut_description <- factor(Pheno_cut$description)
svm_data <- cbind(Expression_cut_t, Pheno_cut_description)

```

```{r}
set.seed(1)
tune_svm <- tune.svm(Pheno_cut_description~., data=svm_data, cost=seq(0.1,1,by=0.1), kernel="linear")

tune_svm$best.parameters

summary(tune_svm)
```



```{r fit1}
fit.1 = svm(Pheno_cut_description ~ ., data=svm_data, kernel="linear", cost=0.1)  
weights.1 = t(fit.1$coefs) %*% fit.1$SV %>% as.data.frame()

absolute_weights_sorted.1 <- as.data.frame(t(sort(abs(weights.1))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.1 <- absolute_weights_sorted.1[1554:15529,] 

rownames(absolute_weights_eliminate10percent.1) <- 1:nrow(absolute_weights_eliminate10percent.1)

#t(weights %>% dplyr::select(ILMN_1762666, ILMN_2185884, ILMN_1790562, ILMN_1738075, ILMN_1806946, ILMN_2394264, ILMN_2208373, ILMN_2376723, ILMN_1714364, ILMN_1737574, ILMN_1773819, ILMN_1743396, ILMN_1668928, ILMN_1715863, ILMN_1737498, ILMN_1777915, ILMN_2157951, ILMN_1748904, ILMN_2356559, ILMN_2167416, ILMN_1666384, ILMN_1732343, ILMN_1690365, ILMN_1801931, ILMN_1653771, ILMN_1756086))

```

```{r fit2}
fit.1_genes_vector <- as.vector(absolute_weights_eliminate10percent.1$Gene)
fit.1_genes <- dput(fit.1_genes_vector)
svm_data.2_genes <- svm_data[,colnames(svm_data) %in% fit.1_genes]
svm_data.2 <- cbind(svm_data.2_genes,Pheno_cut_description)


fit.2 = svm(Pheno_cut_description ~ ., data=svm_data.2, kernel="linear", cost=0.1)  
weights.2 = t(fit.2$coefs) %*% fit.2$SV %>% as.data.frame()

absolute_weights_sorted.2 <- as.data.frame(t(sort(abs(weights.2))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.2 <- absolute_weights_sorted.2[1399:13976,] 

rownames(absolute_weights_eliminate10percent.2) <- 1:nrow(absolute_weights_eliminate10percent.2)
```

```{r fit 3}
fit.2_genes_vector <- as.vector(absolute_weights_eliminate10percent.2$Gene)
fit.2_genes <- dput(fit.2_genes_vector)
svm_data.3_genes <- svm_data.2[,colnames(svm_data.2) %in% fit.2_genes]
svm_data.3 <- cbind(svm_data.3_genes,Pheno_cut_description)


fit.3 = svm(Pheno_cut_description ~ ., data=svm_data.3, kernel="linear", cost=0.1)  
weights.3 = t(fit.3$coefs) %*% fit.3$SV %>% as.data.frame()

absolute_weights_sorted.3 <- as.data.frame(t(sort(abs(weights.3))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.3 <- absolute_weights_sorted.3[1259:12578,] 

rownames(absolute_weights_eliminate10percent.3) <- 1:nrow(absolute_weights_eliminate10percent.3)
```


```{r fit 4}
fit.3_genes_vector <- as.vector(absolute_weights_eliminate10percent.3$Gene)
fit.3_genes <- dput(fit.3_genes_vector)
svm_data.4_genes <- svm_data.3[,colnames(svm_data.3) %in% fit.3_genes]
svm_data.4 <- cbind(svm_data.4_genes,Pheno_cut_description)


fit.4 = svm(Pheno_cut_description ~ ., data=svm_data.4, kernel="linear", cost=0.1)  
weights.4 = t(fit.4$coefs) %*% fit.4$SV %>% as.data.frame()

absolute_weights_sorted.4 <- as.data.frame(t(sort(abs(weights.4))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.4 <- absolute_weights_sorted.4[1133:11320,] 

rownames(absolute_weights_eliminate10percent.4) <- 1:nrow(absolute_weights_eliminate10percent.4)
```


```{r fit5}
fit.4_genes_vector <- as.vector(absolute_weights_eliminate10percent.4$Gene)
fit.4_genes <- dput(fit.4_genes_vector)
svm_data.5_genes <- svm_data.4[,colnames(svm_data.4) %in% fit.4_genes]
svm_data.5 <- cbind(svm_data.5_genes,Pheno_cut_description)


fit.5 = svm(Pheno_cut_description ~ ., data=svm_data.5, kernel="linear", cost=0.1)  
weights.5 = t(fit.5$coefs) %*% fit.5$SV %>% as.data.frame()

absolute_weights_sorted.5 <- as.data.frame(t(sort(abs(weights.5))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.5 <- absolute_weights_sorted.5[1019:10188,] 

rownames(absolute_weights_eliminate10percent.5) <- 1:nrow(absolute_weights_eliminate10percent.5)
```


```{r fit6}
fit.5_genes_vector <- as.vector(absolute_weights_eliminate10percent.5$Gene)
fit.5_genes <- dput(fit.5_genes_vector)
svm_data.6_genes <- svm_data.5[,colnames(svm_data.5) %in% fit.5_genes]
svm_data.6 <- cbind(svm_data.6_genes,Pheno_cut_description)


fit.6 = svm(Pheno_cut_description ~ ., data=svm_data.6, kernel="linear", cost=0.1)  
weights.6 = t(fit.6$coefs) %*% fit.6$SV %>% as.data.frame()

absolute_weights_sorted.6 <- as.data.frame(t(sort(abs(weights.6))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.6 <- absolute_weights_sorted.6[918:9170,] 

rownames(absolute_weights_eliminate10percent.6) <- 1:nrow(absolute_weights_eliminate10percent.6)
```


```{r fit7}
fit.6_genes_vector <- as.vector(absolute_weights_eliminate10percent.6$Gene)
fit.6_genes <- dput(fit.6_genes_vector)
svm_data.7_genes <- svm_data.6[,colnames(svm_data.6) %in% fit.6_genes]
svm_data.7 <- cbind(svm_data.7_genes,Pheno_cut_description)


fit.7 = svm(Pheno_cut_description ~ ., data=svm_data.7, kernel="linear", cost=0.1)  
weights.7 = t(fit.7$coefs) %*% fit.7$SV %>% as.data.frame()

absolute_weights_sorted.7 <- as.data.frame(t(sort(abs(weights.7))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.7 <- absolute_weights_sorted.7[827:8253,] 

rownames(absolute_weights_eliminate10percent.7) <- 1:nrow(absolute_weights_eliminate10percent.7)
```


```{r fit 8}
fit.7_genes_vector <- as.vector(absolute_weights_eliminate10percent.7$Gene)
fit.7_genes <- dput(fit.7_genes_vector)
svm_data.8_genes <- svm_data.7[,colnames(svm_data.7) %in% fit.7_genes]
svm_data.8 <- cbind(svm_data.8_genes,Pheno_cut_description)


fit.8 = svm(Pheno_cut_description ~ ., data=svm_data.8, kernel="linear", cost=0.1)  
weights.8 = t(fit.8$coefs) %*% fit.8$SV %>% as.data.frame()

absolute_weights_sorted.8 <- as.data.frame(t(sort(abs(weights.8))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.8 <- absolute_weights_sorted.7[744:7427,] 

rownames(absolute_weights_eliminate10percent.8) <- 1:nrow(absolute_weights_eliminate10percent.8)
```


```{r fit 9}
fit.8_genes_vector <- as.vector(absolute_weights_eliminate10percent.8$Gene)
fit.8_genes <- dput(fit.8_genes_vector)
svm_data.9_genes <- svm_data.8[,colnames(svm_data.8) %in% fit.8_genes]
svm_data.9 <- cbind(svm_data.9_genes,Pheno_cut_description)


fit.9 = svm(Pheno_cut_description ~ ., data=svm_data.9, kernel="linear", cost=0.1)  
weights.9 = t(fit.9$coefs) %*% fit.9$SV %>% as.data.frame()

absolute_weights_sorted.9 <- as.data.frame(t(sort(abs(weights.9))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

absolute_weights_eliminate10percent.9 <- absolute_weights_sorted.9[662:6601,] 

rownames(absolute_weights_eliminate10percent.9) <- 1:nrow(absolute_weights_eliminate10percent.9)
```


```{r fit10}
fit.9_genes_vector <- as.vector(absolute_weights_eliminate10percent.9$Gene)
fit.9_genes <- dput(fit.9_genes_vector)
svm_data.10_genes <- svm_data.9[,colnames(svm_data.9) %in% fit.9_genes]
svm_data.10 <- cbind(svm_data.10_genes,Pheno_cut_description)


fit.10 = svm(Pheno_cut_description ~ ., data=svm_data.10, kernel="linear", cost=0.1)  
weights.10 = t(fit.10$coefs) %*% fit.10$SV %>% as.data.frame()

absolute_weights_sorted.10 <- as.data.frame(t(sort(abs(weights.10))))  %>% dplyr::rename(weight=V1) %>% tibble::rownames_to_column("Gene")

Genes_251_after10svm <- absolute_weights_sorted.10 %>% arrange(desc(weight)) %>% head(251)

```


```{r}

Gene_genes251.vector <- as.vector(Genes_251_after10svm$Gene)
Gene_genes251 <- dput(Gene_genes251.vector)
Genesdata_genes251.0 <- Genes[rownames(Genes) %in% Gene_genes251,]

paper_251genes <- read.csv("Paper_251genes.csv")

paper_251genes_symbol <- paper_251genes %>% dplyr::select(Symbol)
Genesdata_genes251 <- Genesdata_genes251.0 %>% dplyr::select(Symbol)
overlapping_gene_symbols <- paper_251genes_symbol %>% inner_join(Genesdata_genes251)

Expression_cut_genes251 <- Expression_cut[rownames(Expression_cut) %in% Gene_genes251,]

```

```{r pca data}
# PCA genes
PCA_genes <- Genesdata_genes251.0 %>% dplyr::select(ID, Symbol)

#PCA counts
PCA_counts_TS1 <- as.data.frame(Expression_TS1)[rownames(as.data.frame(Expression_TS1)) %in% Gene_genes251,]
PCA_counts_TS1_genes.df <- PCA_counts_TS1 %>% tibble::rownames_to_column("Gene")
PCA_counts_TS1_vector <- PCA_counts_TS1_genes.df [, "Gene"]
PCA_counts_TS1_genes <- dput(as.character(PCA_counts_TS1_vector))
PCA_counts_Origin <- Expression_cut_genes251[rownames(Expression_cut_genes251) %in% PCA_counts_TS1_genes,]
PCA_counts <- cbind(PCA_counts_Origin, PCA_counts_TS1)

# PCA samples data 
PCA_pheno_origin <- Pheno_cut %>% dplyr::select(`disease state:ch1`) %>% dplyr::rename(disease_state = `disease state:ch1`) %>% mutate(disease_state = case_when(disease_state == "HIV only" ~ "HIV", disease_state == "HIV/TB" ~ "HIV/MTB")) %>% mutate(Data = "Origin") %>% dplyr::rename(Disease_State = disease_state)
PCA_pheno_TS1 <- Pheno_TS1 %>% dplyr::select(`time post initiation of treatment:ch1`, `illness:ch1`) %>% dplyr::rename(disease_state = `time post initiation of treatment:ch1`) %>% mutate(disease_state = case_when(disease_state == "0_months" & `illness:ch1` == "Control" ~ "Controls", disease_state == "0_months" & `illness:ch1` == "PTB" ~ "TB", disease_state == "2_months" ~ "TB (2Mo)", disease_state =="12_months" ~ "TB (12Mo)")) %>% dplyr::select(disease_state) %>% mutate(Data = "TS1") %>% dplyr::rename(Disease_State = disease_state)

PCA_samples <- PCA_pheno_origin %>% rbind(PCA_pheno_TS1)

write.csv(PCA_genes,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_genes.csv", row.names = TRUE)
write.csv(PCA_counts,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_counts.csv", row.names = TRUE)
write.csv(PCA_samples,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_samples.csv", row.names = TRUE)

```

```{r svm score origin}
svm_score_origin <- predict(fit.10, svm_data.10, decision.values = TRUE)
svm_score_origin

SVM_Scores_Origin <- read.csv("SVM_Scores_Origin.csv") %>% dplyr::rename(Sample_ID = 1) %>% mutate(Predicted_Disease = case_when(row_number() %in% c(1:22) ~ "HIV", row_number() %in% c(23:44) ~ "HIV/TB")) %>% mutate(Disease = case_when(row_number() %in% c(1:22) ~ "HIV", row_number() %in% c(23:44) ~ "HIV/TB")) %>% filter(row_number() %in% c(1:43)) %>% arrange(-SVM_Score) 
                                                                                     
colour_graph <- c(rep("#636363",22), rep("#fafcfb", 21))
             
ggplot(SVM_Scores_Origin, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + geom_col(stat = "identity", fill = colour_graph) +  labs(title = "Training Set", y = "SVM Score") + theme(plot.title=element_text(hjust=0.5, size=15), axis.title.x = element_text(hjust = 0.5), axis.title.y = element_text(size=15)) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())                                                                                   
                                                                                                    
```

```{r}
Genesdata_genes251.0 %>% dplyr::select(Accession, Symbol, Definition) %>% dplyr::rename(`Gene Name` = Definition)
```

```{r svm TS1}
Expression_TS1_t <- as.data.frame(t(Expression_TS1_normalized_new))
Pheno_TS1_treatmenttime <- factor(Pheno_TS1_new$`time post initiation of treatment:ch1`)
svm_data_TS1 <- cbind(Expression_TS1_t, Pheno_TS1_treatmenttime)
svm_data_TS1_251 <- svm_data_TS1[,colnames(svm_data_TS1) %in% Gene_genes251] %>% cbind(Pheno_TS1_treatmenttime)

fit_TS1 = svm(Pheno_TS1_treatmenttime ~ ., data=svm_data_TS1_251, kernel="linear", cost=1)  
svm_score_TS1 <- predict(fit_TS1, svm_data_TS1_251, decision.values = TRUE)
svm_score_TS1

SVM_Scores_TS1 <- read.csv("SVM_Scores_TS1.csv")%>% dplyr::rename(Sample_ID = 1)%>% mutate(Predicted_Treatment = case_when(row_number() %in% c(1:12) ~ "0_months", row_number() %in% c(13:19) ~ "2_months")) %>% mutate(Treatment = case_when(row_number() %in% c(1:12) ~ "0_months", row_number() %in% c(13:19) ~ "2_months")) %>% arrange(-SVM_Score) 

colour_graph_TS1 <- c(rep("#636363",12), rep("#fafcfb", 7))

ggplot(SVM_Scores_TS1, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + geom_col(stat = "identity", fill = colour_graph_TS1) +  labs(title = "Test Set 1", y = "SVM Score") + theme(plot.title=element_text(hjust=0.5, size=15), axis.title.x = element_text(hjust = 0.5), axis.title.y = element_text(size=15)) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) 

```



```{r svm TS2}
Expression_TS2_t <- as.data.frame(t(Expression_TS2_normalized))
Pheno_TS2_treatmenttime <- factor(Pheno_TS2$`time post initiation of treatment:ch1`)
svm_data_TS2 <- cbind(Expression_TS2_t, Pheno_TS2_treatmenttime)
svm_data_TS2_251 <- svm_data_TS2[,colnames(svm_data_TS2) %in% Gene_genes251] %>% cbind(Pheno_TS2_treatmenttime)

fit_TS2 = svm(Pheno_TS2_treatmenttime ~ ., data=svm_data_TS2_251, kernel="linear", cost=1)  
svm_score_TS2 <- predict(fit_TS2, svm_data_TS2_251, decision.values = TRUE)
svm_score_TS2

SVM_Scores_TS2<- read.csv("SVM_Scores_TS2.csv")%>% dplyr::rename(Sample_ID = 1)%>% mutate(Predicted_Treatment = case_when(row_number() %in% c(1:7) ~ "0_months", row_number() %in% c(8:14) ~ "12_months")) %>% left_join(Pheno_TS2, by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Treatment, `time post initiation of treatment:ch1`) %>% dplyr::rename(Treatment=4) %>% arrange(-SVM_Score)

colour_graph_TS2 <- c(rep("#636363",4), rep("#fafcfb", 2),rep("#636363",2),rep("#fafcfb", 2),rep("#636363",1),rep("#fafcfb", 3))

ggplot(SVM_Scores_TS2, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + geom_col(stat = "identity", fill = colour_graph_TS2) +  labs(title = "Test Set 2", y = "SVM Score") + theme(plot.title=element_text(hjust=0.5, size=15), axis.title.x = element_text(hjust = 0.5), axis.title.y = element_text(size=15)) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank()) 
```




```{r svm TS3}
Pheno_TS3_illnessupdate <- Pheno_TS3 %>% dplyr::rename(illness = `illness:ch1`) %>% mutate(illness = case_when(illness == "Latent" ~ "Controls/Latent TB", illness == "Control(BCG-)" ~ "Controls/Latent TB", illness == "PTB" ~ "TB", illness== "Control (BCG+)" ~ "Controls/Latent TB"))

Expression_TS3_t <- as.data.frame(t(TS3_normalized.1))
Pheno_TS3_illness <- factor(Pheno_TS3_illnessupdate$illness)
svm_data_TS3 <- cbind(Expression_TS3_t, Pheno_TS3_illness)
svm_data_TS3_251 <- svm_data_TS3[,colnames(svm_data_TS3) %in% Gene_genes251] %>% cbind(Pheno_TS3_illness)

fit_TS3 = svm(Pheno_TS3_illness ~ ., data=svm_data_TS3_251, kernel="linear", cost=1)  
svm_score_TS3 <- predict(fit_TS3, svm_data_TS3_251, decision.values = TRUE)
svm_score_TS3

SVM_Scores_TS2<- read.csv("SVM_Scores_TS2.csv")%>% dplyr::rename(Sample_ID = 1)%>% mutate(Predicted_Treatment = case_when(row_number() %in% c(1:7) ~ "0_months", row_number() %in% c(8:14) ~ "12_months")) %>% left_join(Pheno_TS2, by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Treatment, `time post initiation of treatment:ch1`) %>% dplyr::rename(Treatment=4) %>% arrange(-SVM_Score)
```




```{r svm TS4}
Pheno_TS4_illnessupdate <- Pheno_TS4 %>% dplyr::rename(illness = characteristics_ch1.3) %>% mutate(illness = case_when(illness == "illness: Control (BCG+)" ~ "Controls/Latent TB", illness == "illness: Latent" ~ "Controls/Latent TB", illness == "illness: PTB" ~ "TB"))

Expression_TS4_t <- as.data.frame(t(TS4_normalized.1))
Pheno_TS4_illness <- factor(Pheno_TS4_illnessupdate$illness)
svm_data_TS4 <- cbind(Expression_TS4_t, Pheno_TS4_illness)
svm_data_TS4_251 <- svm_data_TS4[,colnames(svm_data_TS4) %in% Gene_genes251] %>% cbind(Pheno_TS4_illness)

fit_TS4 = svm(Pheno_TS4_illness ~ ., data=svm_data_TS4_251, kernel="linear", cost=1)  
svm_score_TS4 <- predict(fit_TS4, svm_data_TS4_251, decision.values = TRUE)
svm_score_TS4

```




```{r svm TS5}
Pheno_TS5_illnessupdate <- Pheno_TS5 %>% dplyr::rename(illness = `illness:ch1`) %>% mutate(illness = case_when(illness == "LATENT TB" ~ "Latent TB", illness == "PTB" ~ "TB"))

Expression_TS5_t <- as.data.frame(t(TS5_normalized.1))
Pheno_TS5_illness <- factor(Pheno_TS5_illnessupdate$illness)
svm_data_TS5 <- cbind(Expression_TS5_t, Pheno_TS5_illness)
svm_data_TS5_251 <- svm_data_TS5[,colnames(svm_data_TS5) %in% Gene_genes251] %>% cbind(Pheno_TS5_illness)

fit_TS5 = svm(Pheno_TS5_illness ~ ., data=svm_data_TS5_251, kernel="linear", cost=1)  
svm_score_TS5 <- predict(fit_TS5, svm_data_TS5_251, decision.values = TRUE)
svm_score_TS5

```




```{r svm TS6}
#cant do svm cos there's na values for every/ a lot of genes
Pheno_TS6_illnessupdate <- Pheno_TS6 %>% dplyr::rename(illness = characteristics_ch1) %>% mutate(illness = case_when(illness == "disease: LTB" ~ "Latent TB", illness == "disease: PTB" ~ "TB"))

Expression_TS6_t <- as.data.frame(t(TS6_normalized.1))
Pheno_TS6_illness <- factor(Pheno_TS6_illnessupdate$illness)
svm_data_TS6 <- cbind(Expression_TS6_t, Pheno_TS6_illness)
svm_data_TS6_251 <- svm_data_TS6[,colnames(svm_data_TS6) %in% Gene_genes251] %>% cbind(Pheno_TS6_illness) 

fit_TS6 = svm(Pheno_TS6_illness ~ ., data=svm_data_TS6_251, kernel="linear", cost=1)  
svm_score_TS6 <- predict(fit_TS6, svm_data_TS6_251, decision.values = TRUE)
svm_score_TS6

```
