---
title: "Heatmap"
author: "Kevin Guan"
date: '2022-05-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ComplexHeatmap)
library(tidyverse)
library(gplots)

Origin <- getGEO("GSE50834", GSEMatrix = TRUE)[[1]]

Genes251 <- read.csv("251_gene_names.csv") %>% unlist() %>% as.vector()

Pheno = pData(Origin)

Genes = fData(Origin)

Expression <- exprs(Origin)
rnames = row.names(Expression)
cnames = colnames(Expression)

Expression %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 600)) %>% 
  boxplot()

Expression_cut <- Expression %>% 
  as.data.frame() %>% 
  mutate(GSM1230946=(GSM1230903 + GSM1230904)/2) %>%
  dplyr::select(-GSM1230903) %>%
  dplyr::select(-GSM1230904) %>%
  relocate(GSM1230946,.after = GSM1230902) %>%
  dplyr::rename(GSM1230903=GSM1230946)

row.names(Expression_cut) = rnames
colnames(Expression_cut) = cnames[-3]

Pheno_cut <- Pheno %>% filter(title != "HIV infected patient 2_2")

Expression_251 <- Expression_cut[rownames(Expression_cut) %in% Genes251,]
Gene_251_fdata <- Genes[rownames(Genes) %in% keep_genes,]

```

```{r paper 251 genes}
Genes_copy <- Genes
paper_251genes <- read.csv("Paper_251_genes.csv") %>% dplyr::rename(Accession=1) %>% filter(row_number() %in% c(1:251))

Genes_copy$Search_Key = sub("\\..*", "", Genes_copy$Search_Key)
#Genes paper 251 data
Gene_251_paper_fdata <- Genes_copy %>% inner_join(paper_251genes, by=c("Search_Key" = "Accession", "Symbol")) %>% filter(row_number() %in% c(1:251))

keep_genes_paper <- dput(Gene_251_paper_fdata %>% dplyr::select(ID) %>% unlist() %>% as.vector())
                                                                                                              
#Expression paper 251 data
Expression_251_paper <- Expression_cut[rownames(Expression_cut) %in% keep_genes_paper,]
     
```


```{r}


HIV_samples = row.names(filter(Pheno, description == "HIV" ))
HIV_exprs = Expression_251[,colnames(Expression_251) %in% HIV_samples]
HIV_avg_exprs = data.frame(HIV_avg = rowSums(HIV_exprs)/ncol(HIV_exprs))

HIV_TB_samples = row.names(filter(Pheno, description == "HIV/TB co-infection" ))
HIV_TB_exprs = Expression_251[,colnames(Expression_251) %in% HIV_TB_samples]
HIV_TB_avg_exprs = data.frame(HIV_TB_avg = rowSums(HIV_TB_exprs)/ncol(HIV_TB_exprs))

Fc_df = merge(HIV_avg_exprs, HIV_TB_avg_exprs, by = "row.names")

Fc_df$FC = Fc_df$HIV_avg/Fc_df$HIV_TB_avg
Fc_df$Class = c(rep("HIV",251),rep("HIV/TB", 251))



Hmap_df = Expression_251[order(Expression_251$GSM1230925),]
Hmap_df$Gene = row.names(Hmap_df)

pal <- colorpanel(32, "blue", "white", "red")

heatmap(as.matrix(log(Expression_251)), col = pal, labRow = FALSE, labCol = FALSE, xlab = "Sample", ylab = "Genes")

heatmap.2(as.matrix(log(Expression_251)), scale = "none", col = bluered(100), trace = "none", density.info = "none")

Hmap_plot +
  theme(plot.title=element_text(hjust=0.5, size=15), 
        axis.title.x = element_text(hjust = 0.5), 
        axis.title.y = element_text(size=15)) + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

Hmap_plot <- pivot_longer(data = Hmap_df, 
                          cols = c(1:43),
                          names_to = "Class", 
                          values_to = "Abundance")

ggplot(Hmap_plot, aes(x = Class, y = Gene, fill = Abundance)) +
  geom_tile()

sd(c(100,120))
```

```{r heatmap paper 251}
pal <- colorpanel(32, "blue", "white", "red")

heatmap(as.matrix(log(Expression_251_paper)), col = pal)
```

