---
title: "AMED3002 Reproducible Report"
subtitle: "idk"
author: "Kevin Guan, ..."
date: "University of Sydney | Semester 1 2022"
output:
  rmdformats::downcute:
    fig_caption: yes
    self_contained: yes
    number_sections: true 
    df_print: kable
    code_folding: hide
    theme: sandstone
    highlight: tango
    css: 
      - https://use.fontawesome.com/releases/v5.0.6/css/all.css
---
<style type="text/css">

body{ /* Normal  */
      font-size: 14px;
  }
h1, h2 { /* add border to h1 and h2 */
  border-bottom: solid 1px #666;
}
h1 { /* Header 1 */
  font-size: 56px;
  color: Black;
}
h2 { /* Header 2 */
    font-size: 18px;
  color: Black;
}
h3 { /* Header 3 */
  font-size: 16px;
  color: Grey;
}
</style>
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 

library(tidyverse)
library(GEOquery)
library(org.Hs.eg.db)
library(limma)
library(edgeR)
library(Glimma)
library(Homo.sapiens)
library(phyloseq)
library(gtools)
library(e1071)
library(preprocessCore)
```

GEO data analysis help https://sbc.shef.ac.uk/geo_tutorial/tutorial.nb.html

```{r}
Origin <- getGEO("GSE50834", GSEMatrix = TRUE)[[1]]
TS1 <- getGEO("GSE19435", GSEMatrix = TRUE)[[1]]
TS3 <- getGEO("GSE19439", GSEMatrix = TRUE)[[1]]
TS4<- getGEO("GSE19444", GSEMatrix = TRUE)[[1]]
TS5 <- getGEO("GSE19442", GSEMatrix = TRUE)[[1]]
TS6 <- getGEO("GSE40553", GSEMatrix = TRUE)[[1]]
```


```{r}
#Sample(patient) data
Pheno = pData(Origin)

#Gene data 
Genes = fData(Origin)

#gene expression data
Expression <- exprs(Origin)
rnames = row.names(Expression)
cnames = colnames(Expression)

Expression_normalized <- as.data.frame(normalize.quantiles(exprs(Origin)))
Expression_43 <- Expression %>% 
  as.data.frame() %>% 
  mutate(GSM1230946=(GSM1230903 + GSM1230904)/2) %>%
  dplyr::select(-GSM1230903) %>%
  dplyr::select(-GSM1230904) %>%
  relocate(GSM1230946,.after = GSM1230902) %>%
  dplyr::rename(GSM1230903=GSM1230946)

Expression_43_normalized <- as.data.frame(normalize.quantiles(as.matrix(Expression_43)))
Pheno_43 <- Pheno[-c(3),]

Expression %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 1000)) %>% 
  boxplot()

Expression_normalized %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 1000)) %>% 
  boxplot()

Expression_43_normalized %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 1000)) %>% 
  boxplot()

Expression_normal = normalize.quantiles(Expression) %>% as.data.frame()

row.names(Expression_normal) = rnames
colnames(Expression_normal) = cnames

row.names(Expression_43_normalized) = rnames
colnames(Expression_43_normalized) = cnames[-3]
```



```{r}
HIV <- Expression_43_normalized %>% dplyr::select(1:22)
HIV_TB <- Expression_43_normalized %>% dplyr::select(23:43)

hiv1_hivtb <- cbind(HIV %>% dplyr::select(1), HIV_TB)
hiv2_hivtb <- cbind(HIV %>% dplyr::select(2), HIV_TB)
hiv3_hivtb <- cbind(HIV %>% dplyr::select(3), HIV_TB)
hiv4_hivtb <- cbind(HIV %>% dplyr::select(4), HIV_TB)
hiv5_hivtb <- cbind(HIV %>% dplyr::select(5), HIV_TB)
hiv6_hivtb <- cbind(HIV %>% dplyr::select(6), HIV_TB)
hiv7_hivtb <- cbind(HIV %>% dplyr::select(7), HIV_TB)
hiv8_hivtb <- cbind(HIV %>% dplyr::select(8), HIV_TB)
hiv9_hivtb <- cbind(HIV %>% dplyr::select(9), HIV_TB)
hiv10_hivtb <- cbind(HIV %>% dplyr::select(10), HIV_TB)
hiv11_hivtb <- cbind(HIV %>% dplyr::select(11), HIV_TB)
hiv12_hivtb <- cbind(HIV %>% dplyr::select(12), HIV_TB)
hiv13_hivtb <- cbind(HIV %>% dplyr::select(13), HIV_TB)
hiv14_hivtb <- cbind(HIV %>% dplyr::select(14), HIV_TB)
hiv15_hivtb <- cbind(HIV %>% dplyr::select(15), HIV_TB)
hiv16_hivtb <- cbind(HIV %>% dplyr::select(16), HIV_TB)
hiv17_hivtb <- cbind(HIV %>% dplyr::select(17), HIV_TB)
hiv18_hivtb <- cbind(HIV %>% dplyr::select(18), HIV_TB)
hiv19_hivtb <- cbind(HIV %>% dplyr::select(19), HIV_TB)
hiv20_hivtb <- cbind(HIV %>% dplyr::select(20), HIV_TB)
hiv21_hivtb <- cbind(HIV %>% dplyr::select(21), HIV_TB)
hiv22_hivtb <- cbind(HIV %>% dplyr::select(22), HIV_TB)

```


```{r maximum foldchange}

#calculating fold change between samples for all genes 
data = Expression_43_normalized

Keep = c()
for (row in 1:nrow(data)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data)-1)){
    col1 = a
    col2 = a
    while(col2 <= ncol(data)-1) {
      col2 = col2 + 1
      fc_forward = data[row,col1]/data[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data[row,col2]/data[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange$max <- apply(foldchange, MARGIN = 1, FUN = max)
  
  if (max(foldchange$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep = c(Keep, truth)
}

table(Keep)
```


```{r hiv1}

#calculating fold change between hiv/hiv+tb samples for all genes 
data1 = hiv1_hivtb
Keep1 = c()
Keep1.1 = c()
for (row in 1:nrow(data1)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data1)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data1)-1) {
      col2 = col2 + 1
      fc_forward = data1[row,col1]/data1[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data1[row,col2]/data1[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange1 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange1$max <- apply(foldchange1, MARGIN = 1, FUN = max)
  
  if (max(foldchange1$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep1 = c(Keep1, truth)
  Keep1.1 = c(Keep1.1, max(foldchange1$max))
}

table(Keep1)
Keep_hiv1_hivtb <- as.data.frame(Keep1)
Keep1.1.df <- as.data.frame(Keep1.1) %>% dplyr::rename(Fold_Change =Keep1.1)

Keep_hiv1_hivtb_withgenes <- cbind(Keep_hiv1_hivtb,  Expression_43_normalized)
Keep_hiv1_hivtb_withgenes$Keep1 = as.character(Keep_hiv1_hivtb_withgenes$Keep1)
t1 <- Keep_hiv1_hivtb_withgenes %>% filter(Keep1 == "TRUE")

f1 <- Keep_hiv1_hivtb_withgenes %>% filter(Keep1 == "FALSE")

f1g <- tibble::rownames_to_column(f1, "Gene")
f1_gene <- f1g%>% dplyr::select(Gene) 

gene_fc_1<- Keep_hiv1_hivtb_withgenes %>% cbind(Keep1.1.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv2}

#calculating fold change between hiv/hiv+tb samples for all genes 
data2 = hiv2_hivtb
Keep2 = c()
Keep2.2 = c()
for (row in 1:nrow(data2)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data2)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data2)-1) {
      col2 = col2 + 1
      fc_forward = data2[row,col1]/data2[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data2[row,col2]/data2[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange2 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange2$max <- apply(foldchange2, MARGIN = 1, FUN = max)
  
  if (max(foldchange2$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep2 = c(Keep2, truth)
  Keep2.2 = c(Keep2.2, max(foldchange2$max))
}

table(Keep2)
Keep_hiv2_hivtb <- as.data.frame(Keep2)
Keep2.2.df <- as.data.frame(Keep2.2) %>% dplyr::rename(Fold_Change =Keep2.2)

Keep_hiv2_hivtb_withgenes <- cbind(Keep_hiv2_hivtb,  Expression_43_normalized)
Keep_hiv2_hivtb_withgenes$Keep2 = as.character(Keep_hiv2_hivtb_withgenes$Keep2)
t2 <- Keep_hiv2_hivtb_withgenes %>% filter(Keep2 == "TRUE")

f2 <- Keep_hiv2_hivtb_withgenes %>% filter(Keep2 == "FALSE")

f2g <- tibble::rownames_to_column(f2, "Gene")
f2_gene <- f2g%>% dplyr::select(Gene) 

gene_fc_2<- Keep_hiv2_hivtb_withgenes %>% cbind(Keep2.2.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv3}

#calculating fold change between hiv/hiv+tb samples for all genes 
data3 = hiv3_hivtb
Keep3 = c()
Keep3.3=c()
for (row in 1:nrow(data3)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data3)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data3)-1) {
      col2 = col2 + 1
      fc_forward = data3[row,col1]/data3[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data3[row,col2]/data3[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange3 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange3$max <- apply(foldchange3, MARGIN = 1, FUN = max)
  
  if (max(foldchange3$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep3 = c(Keep3, truth)
  Keep3.3 = c(Keep3.3, max(foldchange3$max))
}

table(Keep3)
Keep_hiv3_hivtb <- as.data.frame(Keep3)
Keep3.3.df <- as.data.frame(Keep3.3) %>% dplyr::rename(Fold_Change =Keep3.3)

Keep_hiv3_hivtb_withgenes <- cbind(Keep_hiv3_hivtb,  Expression_43_normalized)
Keep_hiv3_hivtb_withgenes$Keep3 = as.character(Keep_hiv3_hivtb_withgenes$Keep3)
t3 <- Keep_hiv3_hivtb_withgenes %>% filter(Keep3 == "TRUE")

f3 <- Keep_hiv3_hivtb_withgenes %>% filter(Keep3 == "FALSE")

f3g <- tibble::rownames_to_column(f3, "Gene")
f3_gene <- f3g%>% dplyr::select(Gene) 

gene_fc_3<- Keep_hiv3_hivtb_withgenes %>% cbind(Keep3.3.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv4}

#calculating fold change between hiv/hiv+tb samples for all genes 
data4 = hiv4_hivtb
Keep4 = c()
Keep4.4 = c()
for (row in 1:nrow(data4)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data4)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data4)-1) {
      col2 = col2 + 1
      fc_forward = data4[row,col1]/data4[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data4[row,col2]/data4[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange4 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange4$max <- apply(foldchange4, MARGIN = 1, FUN = max)
  
  if (max(foldchange4$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep4 = c(Keep4, truth)
  Keep4.4 = c(Keep4.4, max(foldchange4$max))
}

table(Keep4)
Keep_hiv4_hivtb <- as.data.frame(Keep4)
Keep4.4.df <- as.data.frame(Keep4.4) %>% dplyr::rename(Fold_Change =Keep4.4)

Keep_hiv4_hivtb_withgenes <- cbind(Keep_hiv4_hivtb,  Expression_43_normalized)
Keep_hiv4_hivtb_withgenes$Keep4 = as.character(Keep_hiv4_hivtb_withgenes$Keep4)
t4 <- Keep_hiv4_hivtb_withgenes %>% filter(Keep4 == "TRUE")

f4 <- Keep_hiv4_hivtb_withgenes %>% filter(Keep4 == "FALSE")

f4g <- tibble::rownames_to_column(f4, "Gene")
f4_gene <- f4g%>% dplyr::select(Gene) 

gene_fc_4<- Keep_hiv4_hivtb_withgenes %>% cbind(Keep4.4.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv5}

#calculating fold change between hiv/hiv+tb samples for all genes 
data5 = hiv5_hivtb
Keep5 = c()
Keep5.5=c()
for (row in 1:nrow(data5)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data5)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data5)-1) {
      col2 = col2 + 1
      fc_forward = data5[row,col1]/data5[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data5[row,col2]/data5[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange5 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange5$max <- apply(foldchange5, MARGIN = 1, FUN = max)
  
  if (max(foldchange5$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep5 = c(Keep5, truth)
  Keep5.5 = c(Keep5.5, max(foldchange5$max))
}

table(Keep5)
Keep_hiv5_hivtb <- as.data.frame(Keep5)
Keep5.5.df <- as.data.frame(Keep5.5) %>% dplyr::rename(Fold_Change =Keep5.5)

Keep_hiv5_hivtb_withgenes <- cbind(Keep_hiv5_hivtb,  Expression_43_normalized)
Keep_hiv5_hivtb_withgenes$Keep5 = as.character(Keep_hiv5_hivtb_withgenes$Keep5)
t5 <- Keep_hiv5_hivtb_withgenes %>% filter(Keep5 == "TRUE")

f5 <- Keep_hiv5_hivtb_withgenes %>% filter(Keep5 == "FALSE")

f5g <- tibble::rownames_to_column(f5, "Gene")
f5_gene <- f5g%>% dplyr::select(Gene) 

gene_fc_5<- Keep_hiv5_hivtb_withgenes %>% cbind(Keep5.5.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv6}

#calculating fold change between hiv/hiv+tb samples for all genes 
data6 = hiv6_hivtb
Keep6 = c()
Keep6.6=c()
for (row in 1:nrow(data6)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data6)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data6)-1) {
      col2 = col2 + 1
      fc_forward = data6[row,col1]/data6[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data6[row,col2]/data6[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange6 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange6$max <- apply(foldchange6, MARGIN = 1, FUN = max)
  
  if (max(foldchange6$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep6 = c(Keep6, truth)
  Keep6.6 = c(Keep6.6, max(foldchange6$max))
}

table(Keep6)
Keep_hiv6_hivtb <- as.data.frame(Keep6)
Keep6.6.df <- as.data.frame(Keep6.6) %>% dplyr::rename(Fold_Change =Keep6.6)

Keep_hiv6_hivtb_withgenes <- cbind(Keep_hiv6_hivtb,  Expression_43_normalized)
Keep_hiv6_hivtb_withgenes$Keep6 = as.character(Keep_hiv6_hivtb_withgenes$Keep6)
t6 <- Keep_hiv6_hivtb_withgenes %>% filter(Keep6 == "TRUE")

f6 <- Keep_hiv6_hivtb_withgenes %>% filter(Keep6 == "FALSE")

f6g <- tibble::rownames_to_column(f6, "Gene")
f6_gene <- f6g%>% dplyr::select(Gene) 

gene_fc_6<- Keep_hiv6_hivtb_withgenes %>% cbind(Keep6.6.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv7}

#calculating fold change between hiv/hiv+tb samples for all genes 
data7 = hiv7_hivtb
Keep7 = c()
Keep7.7 =c()
for (row in 1:nrow(data7)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data7)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data7)-1) {
      col2 = col2 + 1
      fc_forward = data7[row,col1]/data7[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data7[row,col2]/data7[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange7 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange7$max <- apply(foldchange7, MARGIN = 1, FUN = max)
  
  if (max(foldchange7$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep7 = c(Keep7, truth)
  Keep7.7 = c(Keep7.7, max(foldchange7$max))
}

table(Keep7)
Keep_hiv7_hivtb <- as.data.frame(Keep7)
Keep7.7.df <- as.data.frame(Keep7.7) %>% dplyr::rename(Fold_Change =Keep7.7)

Keep_hiv7_hivtb_withgenes <- cbind(Keep_hiv7_hivtb,  Expression_43_normalized)
Keep_hiv7_hivtb_withgenes$Keep7 = as.character(Keep_hiv7_hivtb_withgenes$Keep7)
t7 <- Keep_hiv7_hivtb_withgenes %>% filter(Keep7 == "TRUE")

f7 <- Keep_hiv7_hivtb_withgenes %>% filter(Keep7 == "FALSE")

f7g <- tibble::rownames_to_column(f7, "Gene")
f7_gene <- f7g%>% dplyr::select(Gene) 

gene_fc_7<- Keep_hiv7_hivtb_withgenes %>% cbind(Keep7.7.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change)  

```


```{r hiv8}

#calculating fold change between hiv/hiv+tb samples for all genes 
data8 = hiv8_hivtb
Keep8 = c()
Keep8.8=c()
for (row in 1:nrow(data8)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data8)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data8)-1) {
      col2 = col2 + 1
      fc_forward = data8[row,col1]/data8[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data8[row,col2]/data8[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange8 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange8$max <- apply(foldchange8, MARGIN = 1, FUN = max)
  
  if (max(foldchange8$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep8 = c(Keep8, truth)
  Keep8.8 = c(Keep8.8, max(foldchange8$max))
}

table(Keep8)
Keep_hiv8_hivtb <- as.data.frame(Keep8)
Keep8.8.df <- as.data.frame(Keep8.8) %>% dplyr::rename(Fold_Change =Keep8.8)

Keep_hiv8_hivtb_withgenes <- cbind(Keep_hiv8_hivtb,  Expression_43_normalized)
Keep_hiv8_hivtb_withgenes$Keep8 = as.character(Keep_hiv8_hivtb_withgenes$Keep8)
t8 <- Keep_hiv8_hivtb_withgenes %>% filter(Keep8 == "TRUE")

f8 <- Keep_hiv8_hivtb_withgenes %>% filter(Keep8 == "FALSE")

f8g <- tibble::rownames_to_column(f8, "Gene")
f8_gene <- f8g%>% dplyr::select(Gene) 

gene_fc_8<- Keep_hiv8_hivtb_withgenes %>% cbind(Keep8.8.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv9}

#calculating fold change between hiv/hiv+tb samples for all genes 
data9 = hiv9_hivtb
Keep9 = c()
Keep9.9=c()
for (row in 1:nrow(data9)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data9)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data9)-1) {
      col2 = col2 + 1
      fc_forward = data9[row,col1]/data9[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data9[row,col2]/data9[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange9 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange9$max <- apply(foldchange9, MARGIN = 1, FUN = max)
  
  if (max(foldchange9$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep9 = c(Keep9, truth)
  Keep9.9 = c(Keep9.9, max(foldchange9$max))
}

table(Keep9)
Keep_hiv9_hivtb <- as.data.frame(Keep9)
Keep9.9.df <- as.data.frame(Keep9.9) %>% dplyr::rename(Fold_Change =Keep9.9)

Keep_hiv9_hivtb_withgenes <- cbind(Keep_hiv9_hivtb,  Expression_43_normalized)
Keep_hiv9_hivtb_withgenes$Keep9 = as.character(Keep_hiv9_hivtb_withgenes$Keep9)
t9 <- Keep_hiv9_hivtb_withgenes %>% filter(Keep9 == "TRUE")

f9 <- Keep_hiv9_hivtb_withgenes %>% filter(Keep9 == "FALSE")

f9g <- tibble::rownames_to_column(f9, "Gene")
f9_gene <- f9g%>% dplyr::select(Gene) 

gene_fc_9<- Keep_hiv9_hivtb_withgenes %>% cbind(Keep9.9.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv10}

#calculating fold change between hiv/hiv+tb samples for all genes 
data10 = hiv10_hivtb
Keep10 = c()
Keep10.10 =c()
for (row in 1:nrow(data10)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data10)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data10)-1) {
      col2 = col2 + 1
      fc_forward = data10[row,col1]/data10[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data10[row,col2]/data10[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange10 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange10$max <- apply(foldchange10, MARGIN = 1, FUN = max)
  
  if (max(foldchange10$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep10 = c(Keep10, truth)
  Keep10.10 = c(Keep10.10, max(foldchange10$max))
}

table(Keep10)
Keep_hiv10_hivtb <- as.data.frame(Keep10)
Keep10.10.df <- as.data.frame(Keep10.10) %>% dplyr::rename(Fold_Change =Keep10.10)

Keep_hiv10_hivtb_withgenes <- cbind(Keep_hiv10_hivtb,  Expression_43_normalized)
Keep_hiv10_hivtb_withgenes$Keep10 = as.character(Keep_hiv10_hivtb_withgenes$Keep10)
t10 <- Keep_hiv10_hivtb_withgenes %>% filter(Keep10 == "TRUE")

f10 <- Keep_hiv10_hivtb_withgenes %>% filter(Keep10 == "FALSE")

f10g <- tibble::rownames_to_column(f10, "Gene")
f10_gene <- f10g%>% dplyr::select(Gene) 

gene_fc_10<- Keep_hiv10_hivtb_withgenes %>% cbind(Keep10.10.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change)  

```


```{r hiv11}

#calculating fold change between hiv/hiv+tb samples for all genes 
data11 = hiv11_hivtb
Keep11 = c()
Keep11.11 = c()
for (row in 1:nrow(data11)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data11)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data11)-1) {
      col2 = col2 + 1
      fc_forward = data4[row,col1]/data4[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data4[row,col2]/data4[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange11 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange11$max <- apply(foldchange11, MARGIN = 1, FUN = max)
  
  if (max(foldchange11$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep11 = c(Keep11, truth)
  Keep11.11 = c(Keep11.11, max(foldchange11$max))
}

table(Keep11)
Keep_hiv11_hivtb <- as.data.frame(Keep11)
Keep11.11.df <- as.data.frame(Keep11.11) %>% dplyr::rename(Fold_Change =Keep11.11)

Keep_hiv11_hivtb_withgenes <- cbind(Keep_hiv11_hivtb,  Expression_43_normalized)
Keep_hiv11_hivtb_withgenes$Keep11 = as.character(Keep_hiv11_hivtb_withgenes$Keep11)
t11 <- Keep_hiv11_hivtb_withgenes %>% filter(Keep11 == "TRUE")

f11 <- Keep_hiv11_hivtb_withgenes %>% filter(Keep11 == "FALSE")

f11g <- tibble::rownames_to_column(f11, "Gene")
f11_gene <- f11g%>% dplyr::select(Gene) 

gene_fc_11<- Keep_hiv11_hivtb_withgenes %>% cbind(Keep11.11.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv12}

#calculating fold change between hiv/hiv+tb samples for all genes 
data12 = hiv12_hivtb
Keep12 = c()
Keep12.12 =c()
for (row in 1:nrow(data12)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data12)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data12)-1) {
      col2 = col2 + 1
      fc_forward = data12[row,col1]/data12[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data12[row,col2]/data12[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange12 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange12$max <- apply(foldchange12, MARGIN = 1, FUN = max)
  
  if (max(foldchange12$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep12 = c(Keep12, truth)
  Keep12.12 = c(Keep12.12, max(foldchange12$max))
}

table(Keep12)
Keep_hiv12_hivtb <- as.data.frame(Keep12)
Keep12.12.df <- as.data.frame(Keep12.12) %>% dplyr::rename(Fold_Change =Keep12.12)

Keep_hiv12_hivtb_withgenes <- cbind(Keep_hiv12_hivtb,  Expression_43_normalized)
Keep_hiv12_hivtb_withgenes$Keep12 = as.character(Keep_hiv12_hivtb_withgenes$Keep12)
t12 <- Keep_hiv12_hivtb_withgenes %>% filter(Keep12 == "TRUE")

f12 <- Keep_hiv12_hivtb_withgenes %>% filter(Keep12 == "FALSE")

f12g <- tibble::rownames_to_column(f12, "Gene")
f12_gene <- f12g%>% dplyr::select(Gene) 

gene_fc_12<- Keep_hiv12_hivtb_withgenes %>% cbind(Keep12.12.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv13}

#calculating fold change between hiv/hiv+tb samples for all genes 
data13 = hiv13_hivtb
Keep13 = c()
Keep13.13 = c()
for (row in 1:nrow(data13)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data13)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data13)-1) {
      col2 = col2 + 1
      fc_forward = data13[row,col1]/data13[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data13[row,col2]/data13[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange13 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange13$max <- apply(foldchange13, MARGIN = 1, FUN = max)
  
  if (max(foldchange13$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep13 = c(Keep13, truth)
  Keep13.13 = c(Keep13.13, max(foldchange13$max))
}

table(Keep13)
Keep_hiv13_hivtb <- as.data.frame(Keep13)
Keep13.13.df <- as.data.frame(Keep13.13) %>% dplyr::rename(Fold_Change =Keep13.13)

Keep_hiv13_hivtb_withgenes <- cbind(Keep_hiv13_hivtb,  Expression_43_normalized)
Keep_hiv13_hivtb_withgenes$Keep13 = as.character(Keep_hiv13_hivtb_withgenes$Keep13)
t13 <- Keep_hiv13_hivtb_withgenes %>% filter(Keep13 == "TRUE")

f13 <- Keep_hiv13_hivtb_withgenes %>% filter(Keep13 == "FALSE")

f13g <- tibble::rownames_to_column(f13, "Gene")
f13_gene <- f13g%>% dplyr::select(Gene) 

gene_fc_13<- Keep_hiv13_hivtb_withgenes %>% cbind(Keep13.13.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv14}

#calculating fold change between hiv/hiv+tb samples for all genes 
data14 = hiv14_hivtb
Keep14 = c()
Keep14.14 = c()
for (row in 1:nrow(data14)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data14)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data14)-1) {
      col2 = col2 + 1
      fc_forward = data14[row,col1]/data14[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data14[row,col2]/data14[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange14 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange14$max <- apply(foldchange14, MARGIN = 1, FUN = max)
  
  if (max(foldchange14$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep14 = c(Keep14, truth)
  Keep14.14 = c(Keep14.14, max(foldchange14$max))
}

table(Keep14)
Keep_hiv14_hivtb <- as.data.frame(Keep14)
Keep14.14.df <- as.data.frame(Keep14.14) %>% dplyr::rename(Fold_Change =Keep14.14)

Keep_hiv14_hivtb_withgenes <- cbind(Keep_hiv14_hivtb,  Expression_43_normalized)
Keep_hiv14_hivtb_withgenes$Keep14 = as.character(Keep_hiv14_hivtb_withgenes$Keep14)
t14 <- Keep_hiv14_hivtb_withgenes %>% filter(Keep14 == "TRUE")

f14 <- Keep_hiv14_hivtb_withgenes %>% filter(Keep14 == "FALSE")

f14g <- tibble::rownames_to_column(f14, "Gene")
f14_gene <- f14g%>% dplyr::select(Gene) 

gene_fc_14<- Keep_hiv14_hivtb_withgenes %>% cbind(Keep14.14.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv15}

#calculating fold change between hiv/hiv+tb samples for all genes 
data15 = hiv15_hivtb
Keep15 = c()
Keep15.15 = c()
for (row in 1:nrow(data15)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data15)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data15)-1) {
      col2 = col2 + 1
      fc_forward = data15[row,col1]/data15[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data15[row,col2]/data15[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange15 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange15$max <- apply(foldchange15, MARGIN = 1, FUN = max)
  
  if (max(foldchange15$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep15 = c(Keep15, truth)
  Keep15.15 = c(Keep15.15, max(foldchange15$max))
}

table(Keep15)
Keep_hiv15_hivtb <- as.data.frame(Keep15)
Keep15.15.df <- as.data.frame(Keep15.15) %>% dplyr::rename(Fold_Change =Keep15.15)

Keep_hiv15_hivtb_withgenes <- cbind(Keep_hiv15_hivtb,  Expression_43_normalized)
Keep_hiv15_hivtb_withgenes$Keep15 = as.character(Keep_hiv15_hivtb_withgenes$Keep15)
t15 <- Keep_hiv15_hivtb_withgenes %>% filter(Keep15 == "TRUE")

f15 <- Keep_hiv15_hivtb_withgenes %>% filter(Keep15 == "FALSE")

f15g <- tibble::rownames_to_column(f15, "Gene")
f15_gene <- f15g%>% dplyr::select(Gene) 

gene_fc_15<- Keep_hiv15_hivtb_withgenes %>% cbind(Keep15.15.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv16}

#calculating fold change between hiv/hiv+tb samples for all genes 
data16 = hiv16_hivtb
Keep16 = c()
Keep16.16 = c()
for (row in 1:nrow(data16)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data16)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data16)-1) {
      col2 = col2 + 1
      fc_forward = data16[row,col1]/data16[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data16[row,col2]/data16[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange16 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange16$max <- apply(foldchange16, MARGIN = 1, FUN = max)
  
  if (max(foldchange16$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep16 = c(Keep16, truth)
  Keep16.16 = c(Keep16.16, max(foldchange16$max))
}

table(Keep16)
Keep_hiv16_hivtb <- as.data.frame(Keep16)
Keep16.16.df <- as.data.frame(Keep16.16) %>% dplyr::rename(Fold_Change =Keep16.16)

Keep_hiv16_hivtb_withgenes <- cbind(Keep_hiv16_hivtb,  Expression_43_normalized)
Keep_hiv16_hivtb_withgenes$Keep16 = as.character(Keep_hiv16_hivtb_withgenes$Keep16)
t16 <- Keep_hiv16_hivtb_withgenes %>% filter(Keep16 == "TRUE")

f16 <- Keep_hiv16_hivtb_withgenes %>% filter(Keep16 == "FALSE")

f16g <- tibble::rownames_to_column(f16, "Gene")
f16_gene <- f16g%>% dplyr::select(Gene) 

gene_fc_16<- Keep_hiv16_hivtb_withgenes %>% cbind(Keep16.16.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv17}

#calculating fold change between hiv/hiv+tb samples for all genes 
data17 = hiv17_hivtb
Keep17 = c()
Keep17.17 = c()
for (row in 1:nrow(data17)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data17)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data17)-1) {
      col2 = col2 + 1
      fc_forward = data17[row,col1]/data17[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data17[row,col2]/data17[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange17 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange17$max <- apply(foldchange17, MARGIN = 1, FUN = max)
  
  if (max(foldchange17$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep17 = c(Keep17, truth)
  Keep17.17 = c(Keep17.17, max(foldchange17$max))
}

table(Keep17)
Keep_hiv17_hivtb <- as.data.frame(Keep17)
Keep17.17.df <- as.data.frame(Keep17.17) %>% dplyr::rename(Fold_Change =Keep17.17)

Keep_hiv17_hivtb_withgenes <- cbind(Keep_hiv17_hivtb,  Expression_43_normalized)
Keep_hiv17_hivtb_withgenes$Keep17 = as.character(Keep_hiv17_hivtb_withgenes$Keep17)
t17 <- Keep_hiv17_hivtb_withgenes %>% filter(Keep17 == "TRUE")

f17 <- Keep_hiv17_hivtb_withgenes %>% filter(Keep17 == "FALSE")

f17g <- tibble::rownames_to_column(f17, "Gene")
f17_gene <- f17g%>% dplyr::select(Gene) 

gene_fc_17<- Keep_hiv17_hivtb_withgenes %>% cbind(Keep17.17.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change) 

```


```{r hiv18}
#calculating fold change between hiv/hiv+tb samples for all genes 
data18 = hiv18_hivtb
Keep18 = c()
Keep18.18 =c()
for (row in 1:nrow(data18)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data18)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data18)-1) {
      col2 = col2 + 1
      fc_forward = data18[row,col1]/data18[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data18[row,col2]/data18[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange18 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange18$max <- apply(foldchange18, MARGIN = 1, FUN = max)
  
  if (max(foldchange18$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep18 = c(Keep18, truth)
  Keep18.18 = c(Keep18.18, max(foldchange18$max))
}

table(Keep18)
Keep_hiv18_hivtb <- as.data.frame(Keep18)
Keep18.18.df <- as.data.frame(Keep18.18) %>% dplyr::rename(Fold_Change =Keep18.18)

Keep_hiv18_hivtb_withgenes <- cbind(Keep_hiv18_hivtb,  Expression_43_normalized)
Keep_hiv18_hivtb_withgenes$Keep18 = as.character(Keep_hiv18_hivtb_withgenes$Keep18)
t18 <- Keep_hiv18_hivtb_withgenes %>% filter(Keep18 == "TRUE")

f18 <- Keep_hiv18_hivtb_withgenes %>% filter(Keep18 == "FALSE")

f18g <- tibble::rownames_to_column(f18, "Gene")
f18_gene <- f18g%>% dplyr::select(Gene) 

gene_fc_18<- Keep_hiv18_hivtb_withgenes %>% cbind(Keep18.18.df) %>% tibble::rownames_to_column("Gene") %>% dplyr::select(Gene, Fold_Change)  
```


```{r hiv19}
#calculating fold change between hiv/hiv+tb samples for all genes 
data19 = hiv19_hivtb
Keep19 = c()
Keep19.19 =c()
for (row in 1:nrow(data19)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data19)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data19)-1) {
      col2 = col2 + 1
      fc_forward = data19[row,col1]/data19[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data19[row,col2]/data19[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange19 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange19$max <- apply(foldchange19, MARGIN = 1, FUN = max)
  
  if (max(foldchange19$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep19 = c(Keep19, truth)
  Keep19.19 = c(Keep19.19, max(foldchange19$max))
}

table(Keep19)
Keep_hiv19_hivtb <- as.data.frame(Keep19)
Keep19.19.df <- as.data.frame(Keep19.19) %>% dplyr::rename(Fold_Change =Keep19.19)

Keep_hiv19_hivtb_withgenes <- cbind(Keep_hiv19_hivtb,  Expression_43_normalized)
Keep_hiv19_hivtb_withgenes$Keep19 = as.character(Keep_hiv19_hivtb_withgenes$Keep19)
t19 <- Keep_hiv19_hivtb_withgenes %>% filter(Keep19 == "TRUE")

f19 <- Keep_hiv19_hivtb_withgenes %>% filter(Keep19 == "FALSE")

f19g <- tibble::rownames_to_column(f19, "Gene")
f19_gene <- f19g%>% dplyr::select(Gene) 

gene_fc_19<- Keep_hiv19_hivtb_withgenes %>% 
  cbind(Keep19.19.df) %>% 
  tibble::rownames_to_column("Gene") %>% 
  dplyr::select(Gene, Fold_Change) 
```


```{r hiv20}

#calculating fold change between hiv/hiv+tb samples for all genes 
data20 = hiv20_hivtb
Keep20 = c()
Keep20.20 = c()
for (row in 1:nrow(data20)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data20)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data20)-1) {
      col2 = col2 + 1
      fc_forward = data20[row,col1]/data20[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data20[row,col2]/data20[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange20 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange20$max <- apply(foldchange20, MARGIN = 1, FUN = max)
  
  if (max(foldchange20$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep20 = c(Keep20, truth)
  Keep20.20 = c(Keep20.20, max(foldchange20$max))
}

table(Keep20)
Keep_hiv20_hivtb <- as.data.frame(Keep20)
Keep20.20.df <- as.data.frame(Keep20.20) %>% dplyr::rename(Fold_Change =Keep20.20)

Keep_hiv20_hivtb_withgenes <- cbind(Keep_hiv20_hivtb,  Expression_43_normalized)
Keep_hiv20_hivtb_withgenes$Keep20 = as.character(Keep_hiv20_hivtb_withgenes$Keep20)
t20 <- Keep_hiv20_hivtb_withgenes %>% filter(Keep20 == "TRUE")

f20 <- Keep_hiv20_hivtb_withgenes %>% filter(Keep20 == "FALSE")

f20g <- tibble::rownames_to_column(f20, "Gene")
f20_gene <- f20g%>% dplyr::select(Gene) 

gene_fc_20<- Keep_hiv20_hivtb_withgenes %>% 
  cbind(Keep20.20.df) %>% 
  tibble::rownames_to_column("Gene") %>%
  dplyr::select(Gene, Fold_Change)
```


```{r hiv21}
#calculating fold change between hiv/hiv+tb samples for all genes 
data21 = hiv21_hivtb
Keep21 = c()
Keep21.21 = c()
for (row in 1:nrow(data21)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data21)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data21)-1) {
      col2 = col2 + 1
      fc_forward = data21[row,col1]/data21[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data21[row,col2]/data21[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange21 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange21$max <- apply(foldchange21, MARGIN = 1, FUN = max)
  
  if (max(foldchange21$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep21 = c(Keep21, truth)
  Keep21.21 = c(Keep21.21, max(foldchange21$max))
}

table(Keep21)
Keep_hiv21_hivtb <- as.data.frame(Keep21)
Keep21.21.df <- as.data.frame(Keep21.21) %>% dplyr::rename(Fold_Change =Keep21.21)

Keep_hiv21_hivtb_withgenes <- cbind(Keep_hiv21_hivtb,  Expression_43_normalized)
Keep_hiv21_hivtb_withgenes$Keep21 = as.character(Keep_hiv21_hivtb_withgenes$Keep21)
t21 <- Keep_hiv21_hivtb_withgenes %>% filter(Keep21 == "TRUE")

f21 <- Keep_hiv21_hivtb_withgenes %>% filter(Keep21 == "FALSE")

f21g <- tibble::rownames_to_column(f21, "Gene")
f21_gene <- f21g%>% dplyr::select(Gene) 

gene_fc_21<- Keep_hiv21_hivtb_withgenes %>% 
  cbind(Keep21.21.df) %>% 
  tibble::rownames_to_column("Gene") %>%
  dplyr::select(Gene, Fold_Change)
```


```{r hiv22}
#calculating fold change between hiv/hiv+tb samples for all genes 
data22 = hiv22_hivtb
Keep22 = c()
Keep22.22 = c()
for (row in 1:nrow(data22)) {
  changes_forward = c()
  names_forward = c()
  changes_backward = c()
  names_backward = c()
  for (a in 1:(ncol(data22)-1)){
    col1 = 1
    col2 = a
    while(col2 <= ncol(data22)-1) {
      col2 = col2 + 1
      fc_forward = data22[row,col1]/data22[row,col2]
      changes_forward = c(changes_forward, fc_forward)
      
      fc_backward = data22[row,col2]/data22[row,col1]
      changes_backward = c(changes_backward, fc_backward)
    }
  }
  foldchange22 = data.frame(change_f = changes_forward, 
                          change_b = changes_backward)
  foldchange22$max <- apply(foldchange22, MARGIN = 1, FUN = max)
  
  if (max(foldchange22$max) <1.2) {
    truth = FALSE
  }
  else {
    truth = TRUE
  }
  
  Keep22 = c(Keep22, truth)
  Keep22.22 = c(Keep22.22, max(foldchange22$max))
}

table(Keep22)
Keep_hiv22_hivtb <- as.data.frame(Keep22)
Keep22.22.df <- as.data.frame(Keep22.22) %>% dplyr::rename(Fold_Change =Keep22.22)

Keep_hiv22_hivtb_withgenes <- cbind(Keep_hiv22_hivtb,  Expression_43_normalized)
Keep_hiv22_hivtb_withgenes$Keep22 = as.character(Keep_hiv22_hivtb_withgenes$Keep22)
t22 <- Keep_hiv22_hivtb_withgenes %>% filter(Keep22 == "TRUE")

f22 <- Keep_hiv22_hivtb_withgenes %>% filter(Keep22 == "FALSE")

f22g <- tibble::rownames_to_column(f22, "Gene")
f22_gene <- f22g%>% dplyr::select(Gene) 

gene_fc_22<- Keep_hiv22_hivtb_withgenes %>% 
  cbind(Keep22.22.df) %>% 
  tibble::rownames_to_column("Gene") %>% 
  dplyr::select(Gene, Fold_Change)

#%>% dplyr::rename(truestatus = Keep22) %>% filter(truestatus == "TRUE")
```



```{r}
#Genes to delete
Genes_to_delete <- f1_gene %>% 
  full_join(f2_gene) %>% 
  full_join(f3_gene) %>% 
  full_join(f4_gene) %>% 
  full_join(f5_gene) %>% 
  full_join(f6_gene) %>% 
  full_join(f7_gene) %>% 
  full_join(f8_gene) %>% 
  full_join(f9_gene) %>% 
  full_join(f10_gene) %>% 
  full_join(f11_gene) %>% 
  full_join(f12_gene) %>% 
  full_join(f13_gene) %>% 
  full_join(f14_gene) %>% 
  full_join(f15_gene) %>% 
  full_join(f16_gene) %>% 
  full_join(f17_gene) %>% 
  full_join(f18_gene) %>% 
  full_join(f19_gene) %>% 
  full_join(f20_gene) %>% 
  full_join(f21_gene) %>% 
  full_join(f22_gene)

#Delete genes 
genes_to_delete <- as.vector(Genes_to_delete$Gene)
genes_to_delete.1 <- dput(genes_to_delete)

# Data with genes deleted
Expression_genes_deleted <- Expression_43_normalized[!(rownames(Expression_43_normalized) %in% genes_to_delete.1),]

```


```{r functions}
svmRFE.wrap <- function(test.fold, X, ...) {
# Wrapper to run svmRFE function while omitting a given test fold
    train.data = X[-test.fold, ]
    test.data  = X[test.fold, ]
    
    # Rank the features
    features.ranked = svmRFE(train.data, ...)
    
    return(list(feature.ids=features.ranked, train.data.ids=row.names(train.data), test.data.ids=row.names(test.data)))
}

svmRFE <- function(X, k=1, cut.above=300) {
# Feature selection with Multiple SVM Recursive Feature Elimination (RFE) algorithm
    n = ncol(X) - 1
    
    # Scale data up front so it doesn't have to be redone each pass
    cat('Scaling data...')
    X[, -1] = scale(X[, -1])
    cat('Done!\n')
    flush.console()
    
    pb = txtProgressBar(1, n, 1, style=3)

    i.surviving = 1:n
    i.ranked    = n
    ranked.list = vector(length=n)

    # Recurse through all the features
    while(length(i.surviving) > 0) {
        if(k > 1) {
            # Subsample to obtain multiple weights vectors (i.e. mSVM-RFE)            
            folds = rep(1:k, len=nrow(X))[sample(nrow(X))]
            folds = lapply(1:k, function(x) which(folds == x))
            
            # Obtain weights for each training set
            w = lapply(folds, getWeights, X[, c(1, 1+i.surviving)])
            w = do.call(rbind, w)
            
            # Normalize each weights vector
            w = t(apply(w, 1, function(x) x / sqrt(sum(x^2))))
            
            # Compute ranking criteria
            v    = w * w
            vbar = apply(v, 2, mean)
            vsd  = apply(v, 2, sd)
            c    = vbar / vsd
        } else {
            # Only do 1 pass (i.e. regular SVM-RFE)
            w = getWeights(NULL, X[, c(1, 1+i.surviving)])
            c = w * w
        }

        # Rank the features
        ranking = sort(c, index.return=T)$ix
        if(length(i.surviving) == 1) {
            ranking = 1
        }
        
        if(length(i.surviving) > cut.above) {
            # Cut features by 10%
            nfeat = length(i.surviving)
            ncut  = round(nfeat / 10)
            n     = nfeat - ncut
        } else ncut = 1
        
        # Update feature list
        ranked.list[i.ranked:(i.ranked-ncut+1)] = i.surviving[ranking[1:ncut]]
        i.ranked    = i.ranked - ncut
        i.surviving = i.surviving[-ranking[1:ncut]]

        setTxtProgressBar(pb, n-length(i.surviving))
        flush.console()
    }
    
    close(pb)

    return (ranked.list)
}

getWeights <- function(test.fold, X) {
# Fit a linear SVM model and obtain feature weights
    train.data = X
    if(!is.null(test.fold)) train.data = X[-test.fold, ]
    
    svmModel = svm(train.data[, -1], train.data[, 1], cost=10, cachesize=500,
    scale=F, type="C-classification", kernel="linear")
    
    t(svmModel$coefs) %*% svmModel$SV
}

WriteFeatures <- function(results, input, save=T, file='features_ranked.txt') {
# Compile feature rankings across multiple folds
    featureID = sort(apply(sapply(results, function(x) sort(x$feature, index.return=T)$ix), 1, mean), index=T)$ix
    avg.rank  = sort(apply(sapply(results, function(x) sort(x$feature, index.return=T)$ix), 1, mean), index=T)$x
    feature.name = colnames(input[, -1])[featureID]
    features.ranked = data.frame(FeatureName=feature.name, FeatureID=featureID, AvgRank=avg.rank)
    if(save==T) {
        write.table(features.ranked, file=file, quote=F, row.names=F)
    } else {
        features.ranked
    }
}

FeatSweep.wrap <- function(i, results, input) {
# Wrapper to estimate generalization error across all hold-out folds, for a given number of top features
    svm.list = lapply(results, function(x) tune(svm,
                      train.x      = input[x$train.data.ids, 1+x$feature.ids[1:i]],
                      train.y      = input[x$train.data.ids, 1],
                      validation.x = input[x$test.data.ids, 1+x$feature.ids[1:i]],
                      validation.y = input[x$test.data.ids, 1],
                      # Optimize SVM hyperparamters
                      ranges       = tune(svm,
                                          train.x = input[x$train.data.ids, 1+x$feature.ids[1:i]],
                                          train.y = input[x$train.data.ids, 1],
                                          ranges  = list(gamma=2^(-12:0), cost=2^(-6:6)))$best.par,
                      tunecontrol  = tune.control(sampling='fix'))$perf)
        
    error = mean(sapply(svm.list, function(x) x$error))
    return(list(svm.list=svm.list, error=error))
}

PlotErrors <- function(errors, errors2=NULL, no.info=0.5, ylim=range(c(errors, errors2), na.rm=T), xlab='Number of Features',  ylab='10x CV Error') {
# Makes a plot of average generalization error vs. number of top features
    AddLine <- function(x, col='black') {
        lines(which(!is.na(errors)), na.omit(x), col=col)
        points(which.min(x), min(x, na.rm=T), col='red')
        text(which.min(x), min(x, na.rm=T), paste(which.min(x), '-', format(min(x, na.rm=T), dig=3)), pos=4, col='red', cex=0.75)
    }
    
    plot(errors, type='n', ylim=ylim, xlab=xlab, ylab=ylab)
    AddLine(errors)
    if(!is.null(errors2)) AddLine(errors2, 'gray30')
    abline(h=no.info, lty=3)
}
```


```{r testing}
X = as.data.frame(t(Expression)) 
y = factor(Pheno$description)
test = cbind(y,X)
input = test

nfold = 10
nrows = nrow(input)
folds = rep(1:nfold, len=nrows)[sample(nrows)]
folds = lapply(1:nfold, function(x) which(folds == x))
results = lapply(folds, svmRFE.wrap, input, k=10, cut.above=300)

names = WriteFeatures(results = results, input = test, save = F)

indexes = names$FeatureName[1:20]

Genes[colnames(test[,indexes]),]$Accession
```


```{r testing}
X.1 = as.data.frame(t(Expression_43_normalized)) 
y.1 = factor(Pheno_43$description)
test.1 = cbind(y.1,X.1)
input.1 = test.1

nfold = 10
nrows.1 = nrow(input.1)
folds = rep(1:nfold, len=nrows.1)[sample(nrows.1)]
folds = lapply(1:nfold, function(x) which(folds == x))
results.1 = lapply(folds, svmRFE.wrap, input.1, k=10, cut.above=300)

names.1 = WriteFeatures(results = results.1, input = test.1, save = F)

indexes.1 = names.1$FeatureName[1:20]
test.1
Genes[colnames(test.1[,indexes.1]),]$Accession



```


```{r testing Expression_genes_deleted}
X.2 = as.data.frame(t(Expression_genes_deleted)) 
y.2 = factor(Pheno_43$description)
test.2 = cbind(y.2,X.2)
input.2 = test.2

nfold = 10
nrows.2 = nrow(input.2)
folds = rep(1:nfold, len=nrows.2)[sample(nrows.2)]
folds = lapply(1:nfold, function(x) which(folds == x))
results.2 = lapply(folds, svmRFE.wrap, input.2, k=10, cut.above=300)

names.2 = WriteFeatures(results = results.2, input = test.2, save = F)

indexes.2 = names.2$FeatureName[1:20]
test.2
Genes[colnames(test.2[,indexes.2]),]$Accession

names.2$FeatureName

Accession_251 <- as.data.frame(Genes[colnames(test.2[,1:252]),]$Accession) %>% na.omit()

Symbol_251 <- as.data.frame(Genes[colnames(test.2[,1:252]),]$Symbol) %>% na.omit()

GeneName_251 <- as.data.frame(Genes[colnames(test.2[,1:252]),]$Definition) %>% na.omit()

```


```{r 251 gene table}
Expression_genes_deleted_fc <- Expression_genes_deleted %>% 
  tibble::rownames_to_column("Gene") %>% 
  left_join(gene_fc_1) %>% 
  left_join(gene_fc_2, by="Gene") %>% 
  left_join(gene_fc_3, by="Gene") %>% 
  left_join(gene_fc_4, by="Gene") %>% 
  left_join(gene_fc_5, by="Gene") %>% 
  left_join(gene_fc_6, by="Gene") %>% 
  left_join(gene_fc_7, by="Gene") %>% 
  left_join(gene_fc_8, by="Gene") %>% 
  left_join(gene_fc_9, by="Gene") %>% 
  left_join(gene_fc_10, by="Gene") %>% 
  left_join(gene_fc_11, by="Gene") %>% 
  left_join(gene_fc_12, by="Gene") %>% 
  left_join(gene_fc_13, by="Gene") %>% 
  left_join(gene_fc_14, by="Gene") %>% 
  left_join(gene_fc_15, by="Gene") %>% 
  left_join(gene_fc_16, by="Gene") %>% 
  left_join(gene_fc_17, by="Gene") %>% 
  left_join(gene_fc_18, by="Gene") %>% 
  left_join(gene_fc_19, by="Gene") %>% 
  left_join(gene_fc_20, by="Gene") %>% 
  left_join(gene_fc_21, by="Gene") %>% 
  left_join(gene_fc_22, by="Gene") 

fc1 <- Expression_genes_deleted_fc %>% dplyr::select(45)%>% dplyr::rename(Fold_Change=1)
fc2 <- Expression_genes_deleted_fc %>% dplyr::select(46)%>% dplyr::rename(Fold_Change=1)
fc3 <- Expression_genes_deleted_fc %>% dplyr::select(47)%>% dplyr::rename(Fold_Change=1)
fc4 <- Expression_genes_deleted_fc %>% dplyr::select(48)%>% dplyr::rename(Fold_Change=1)
fc5 <- Expression_genes_deleted_fc %>% dplyr::select(49)%>% dplyr::rename(Fold_Change=1)
fc6 <- Expression_genes_deleted_fc %>% dplyr::select(50)%>% dplyr::rename(Fold_Change=1)
fc7 <- Expression_genes_deleted_fc %>% dplyr::select(51)%>% dplyr::rename(Fold_Change=1)
fc8 <- Expression_genes_deleted_fc %>% dplyr::select(52)%>% dplyr::rename(Fold_Change=1)
fc9 <- Expression_genes_deleted_fc %>% dplyr::select(53)%>% dplyr::rename(Fold_Change=1)
fc10 <- Expression_genes_deleted_fc %>% dplyr::select(54)%>% dplyr::rename(Fold_Change=1)
fc11 <- Expression_genes_deleted_fc %>% dplyr::select(55)%>% dplyr::rename(Fold_Change=1)
fc12 <- Expression_genes_deleted_fc %>% dplyr::select(56)%>% dplyr::rename(Fold_Change=1)
fc13 <- Expression_genes_deleted_fc %>% dplyr::select(57)%>% dplyr::rename(Fold_Change=1)
fc14 <- Expression_genes_deleted_fc %>% dplyr::select(58)%>% dplyr::rename(Fold_Change=1)
fc15 <- Expression_genes_deleted_fc %>% dplyr::select(59)%>% dplyr::rename(Fold_Change=1)
fc16 <- Expression_genes_deleted_fc %>% dplyr::select(60)%>% dplyr::rename(Fold_Change=1)
fc17 <- Expression_genes_deleted_fc %>% dplyr::select(61)%>% dplyr::rename(Fold_Change=1)
fc18 <- Expression_genes_deleted_fc %>% dplyr::select(62)%>% dplyr::rename(Fold_Change=1)
fc19 <- Expression_genes_deleted_fc %>% dplyr::select(63)%>% dplyr::rename(Fold_Change=1)
fc20 <- Expression_genes_deleted_fc %>% dplyr::select(64)%>% dplyr::rename(Fold_Change=1)
fc21 <- Expression_genes_deleted_fc %>% dplyr::select(65)%>% dplyr::rename(Fold_Change=1)
fc22 <- Expression_genes_deleted_fc %>% dplyr::select(66)%>% dplyr::rename(Fold_Change=1)

#max fold change
Maxfc_gene_251 <- pmax(fc1,fc2,fc3,fc4,fc5,fc6,fc7,fc8,fc9,fc10,fc11,fc12,fc13,fc14,fc15,fc16,fc17,fc18,fc19,fc20,fc21,fc22) %>% head(251)

Genes_251_Rank <- cbind(Accession_251, Symbol_251, GeneName_251, Maxfc_gene_251) %>% 
  tibble::rownames_to_column("Rank") 
Genes_251_Rank$Rank = as.numeric(Genes_251_Rank$Rank)

#Top 251 Genes
Genes_251 <- Genes_251_Rank %>% mutate(Rank = Rank -1) %>%
  dplyr::rename(Accession=2, Symbol=3,`Gene Name`=4, `Fold Change`=5) %>%
  relocate(Rank,.after=`Gene Name`)
#Top 20 Genes
Genes_20 <- Genes_251 %>% head(20)%>%
  relocate(Rank ,.after=`Gene Name`)


write.csv(Genes_251,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\Genes_251.csv", row.names = FALSE)
write.csv(Genes_20,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\Genes_20.csv", row.names = FALSE)
```

