---
title: "251_genes.1"
author: "Christina Lauw"
date: '2022-05-19'
output: html_document
---

</style>
```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 

library(tidyverse)
library(GEOquery)
library(org.Hs.eg.db)
library(limma)
library(edgeR)
library(Glimma)
library(Homo.sapiens)
library(phyloseq)
library(gtools)
library(e1071)
library(caret)
library(ROCR)
library(preprocessCore)
```


```{r paper 251 genes}
Genes_copy <- Genes
paper_251genes <- read.csv("Paper_251_genes.csv") %>% dplyr::rename(Accession=1) %>% filter(row_number() %in% c(1:251))

Genes_copy$Search_Key = sub("\\..*", "", Genes_copy$Search_Key)
Genes_copy %>% inner_join(paper_251genes, by=c("Search_Key" = "Accession", "Symbol"))
```



```{r Read in 251 genes}
Genes251 <- read.csv("251_gene_names.csv") %>% unlist() %>% as.vector()
keep_genes <- dput(Genes251)

Origin <- getGEO("GSE50834", GSEMatrix = TRUE)[[1]]

Pheno = pData(Origin)

Genes = fData(Origin)

Expression <- exprs(Origin)
rnames = row.names(Expression)
cnames = colnames(Expression)

Expression %>% 
  as.data.frame() %>% 
  filter_all(all_vars(. < 600)) %>% 
  boxplot()

Expression_cut <- Expression %>% 
  as.data.frame() %>% 
  mutate(GSM1230946=(GSM1230903 + GSM1230904)/2) %>%
  dplyr::select(-GSM1230903) %>%
  dplyr::select(-GSM1230904) %>%
  relocate(GSM1230946,.after = GSM1230902) %>%
  dplyr::rename(GSM1230903=GSM1230946)

row.names(Expression_cut) = rnames
colnames(Expression_cut) = cnames[-3]

Pheno_cut <- Pheno %>% filter(title != "HIV infected patient 2_2")

Expression_251 <- Expression_cut[rownames(Expression_cut) %in% Genes251,]
Gene_251_fdata <- Genes[rownames(Genes) %in% keep_genes,]
```


```{r pca data}
# PCA genes
PCA_genes <- Gene_251_fdata %>% dplyr::select(ID, Symbol)

#PCA counts
PCA_counts_TS1 <- as.data.frame(Expression_TS1)[rownames(as.data.frame(Expression_TS1)) %in% keep_genes,]
PCA_counts_TS1_genes.df <- PCA_counts_TS1 %>% tibble::rownames_to_column("Gene")
PCA_counts_TS1_vector <- PCA_counts_TS1_genes.df [, "Gene"]
PCA_counts_TS1_genes <- dput(as.character(PCA_counts_TS1_vector))
PCA_counts_Origin <- Expression_251[rownames(Expression_251) %in% PCA_counts_TS1_genes,]
PCA_counts <- cbind(PCA_counts_Origin, PCA_counts_TS1)

# PCA samples data 
PCA_pheno_origin <- Pheno_cut %>% dplyr::select(`disease state:ch1`) %>% dplyr::rename(disease_state = `disease state:ch1`) %>% mutate(disease_state = case_when(disease_state == "HIV only" ~ "HIV", disease_state == "HIV/TB" ~ "HIV/MTB")) %>% mutate(Data = "Origin") %>% dplyr::rename(Disease_State = disease_state)
PCA_pheno_TS1 <- Pheno_TS1 %>% dplyr::select(`time post initiation of treatment:ch1`, `illness:ch1`) %>% dplyr::rename(disease_state = `time post initiation of treatment:ch1`) %>% mutate(disease_state = case_when(disease_state == "0_months" & `illness:ch1` == "Control" ~ "Controls", disease_state == "0_months" & `illness:ch1` == "PTB" ~ "TB", disease_state == "2_months" ~ "TB (2Mo)", disease_state =="12_months" ~ "TB (12Mo)")) %>% dplyr::select(disease_state) %>% mutate(Data = "TS1") %>% dplyr::rename(Disease_State = disease_state)

PCA_samples <- PCA_pheno_origin %>% rbind(PCA_pheno_TS1)

write.csv(PCA_genes,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_genes.csv", row.names = TRUE)
write.csv(PCA_counts,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_counts.csv", row.names = TRUE)
write.csv(PCA_samples,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\PCA_samples.csv", row.names = TRUE)

```


```{r svm score origin}
Expression_251_origin_t <- as.data.frame(t(Expression_251))
Pheno_251_origin_disease <- factor(Pheno_cut$description, levels = c("HIV/TB co-infection", "HIV"), labels = c("HIV/TB co-infection", "HIV"))
svm_data.10_new <- cbind(Expression_251_origin_t, Pheno_251_origin_disease)

fit.10_new <- svm(Pheno_251_origin_disease ~ ., data=svm_data.10_new, kernel="linear", type = "C-classification", cost=1)  

svm_score_origin <- predict(fit.10_new, Expression_251_origin_t, decision.values = TRUE)


SVM_Scores_Origin <- read.csv("SVM_Scores_Origin.csv") %>% 
  dplyr::rename(Sample_ID = 1) %>% 
  mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "HIV/TB co-infection", SVM_Score>=0 ~ "HIV")) %>% 
  mutate(SVM_Score = -SVM_Score) %>% 
  left_join(Pheno,by=c("Sample_ID" = "geo_accession")) %>% 
  dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, description) %>% 
  dplyr::rename(illness = description)

                                                                                     
colour_graph <- c(rep("#636363",22), rep("#fafcfb", 21)) 
             
ggplot(SVM_Scores_Origin, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + 
  geom_col(stat = "identity", fill = colour_graph, color = "black") +
  labs(title = "Training Set", y = "SVM Score") + 
  theme_minimal() +
  theme(plot.title=element_text(hjust=0.5, size=15), 
        axis.title.x = element_text(hjust = 0.5), 
        axis.title.y = element_text(size=15)) + 
  theme(axis.title.x=element_blank(), 
        axis.text.x=element_blank(), 
        axis.ticks.x=element_blank()) 

```


```{r 251 gene table}
Genes_251_fc <- Origin_genes_withfc %>% filter(Gene %in% keep_genes)

Gene_251_Table <- Gene_251_fdata %>% dplyr::select(Accession, Symbol, Definition, ID) %>% dplyr::rename(`Gene Name` = Definition) %>% left_join(Genes_251_fc, by=c("ID" = "Gene")) %>% mutate(Rank = 1:251) %>% dplyr::select(Accession, Symbol, `Gene Name`, Rank, Fold_Change)

Gene_20_Table <- Gene_251_Table %>% head(20)


write.csv(Gene_251_Table,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\Gene_251_Table.csv", row.names = FALSE)
write.csv(Gene_20_Table,"C:\\Users\\lauwc\\OneDrive\\Documents\\Uni 2022-\\AMED3002\\Reproducible_Report\\AMED3002-Reproducible-Report\\Gene_20_Table.csv", row.names = FALSE)


paper_251genes <- read.csv("Paper_251_genes.csv") %>% dplyr::rename(Accession=1) %>% filter(row_number() %in% c(1:251))

paper_251genesID <- Genes %>% inner_join(paper_251genes, by="Symbol") %>% dplyr::select(ID)

Gene_251_fdata %>% inner_join(paper_251genesID, by="ID")
                              
```



```{r svm TS1}
Expression_TS1_t <- as.data.frame(t(Expression_TS1_normalized_new))
Pheno_TS1_treatmenttime <- factor(Pheno_TS1_new$`time post initiation of treatment:ch1`)
svm_data_TS1 <- cbind(Expression_TS1_t, Pheno_TS1_treatmenttime)
svm_data_TS1_251_draft <- svm_data_TS1[,colnames(svm_data_TS1) %in% keep_genes] 
svm_data_TS1_251 <- cbind(svm_data_TS1_251_draft, Pheno_TS1_treatmenttime) %>% dplyr::select(-ILMN_1738075)

sum(is.na(Expression_TS1_t))

fit_TS1 = svm(Pheno_TS1_treatmenttime~., data=svm_data_TS1_251, kernel="linear", type = "C-classification", cost=1) 

svm_score_TS1 <- predict(fit_TS1, svm_data_TS1_251, decision.values = TRUE)
svm_score_TS1

SVM_Scores_TS1 <- read.csv("SVM_Scores_TS1.csv") %>% dplyr::rename(Sample_ID = 1) %>% 
  mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "TB (2 mo)", SVM_Score>=0 ~ "Controls")) %>% 
    mutate(SVM_Score = -SVM_Score) %>% 
  left_join(Pheno_TS1_new,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, `time post initiation of treatment:ch1`) %>% dplyr::rename(illness = `time post initiation of treatment:ch1`) %>% mutate(illness= case_when(illness=="0_months" ~ "Controls", illness == "2_months" ~ "TB (2 mo)"))

colour_graph_TS1 <- c(rep("#636363",12), rep("#fafcfb", 7))

ggplot(SVM_Scores_TS1, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + 
  geom_col(stat = "identity", fill = colour_graph_TS1, color = "black") +  
  labs(title = "Test Set 1", y = "SVM Score") + 
  theme_classic() + 
  theme(plot.title=element_text(hjust=0.5, size=15), 
        axis.title.x = element_text(hjust = 0.5), 
        axis.title.y = element_text(size=15)) + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) 

```



```{r svm TS2}
Expression_TS2_t <- as.data.frame(t(Expression_TS2_normalized))
Pheno_TS2_treatmenttime <- factor(Pheno_TS2$`time post initiation of treatment:ch1`)
svm_data_TS2 <- cbind(Expression_TS2_t, Pheno_TS2_treatmenttime)
svm_data_TS2_251 <- svm_data_TS2[,colnames(svm_data_TS2) %in% keep_genes] %>% cbind(Pheno_TS2_treatmenttime) %>% dplyr::select(-ILMN_1738075) 

fit_TS2 = svm(Pheno_TS2_treatmenttime ~ ., data=svm_data_TS2_251, kernel="linear", cost=1)  
svm_score_TS2 <- predict(fit_TS2, svm_data_TS2_251, decision.values = TRUE)
svm_score_TS2

SVM_Scores_TS2<- read.csv("SVM_Scores_TS2.csv")%>% dplyr::rename(Sample_ID = 1)%>% 
  mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "TB (12 mo)", SVM_Score>=0 ~ "TB")) %>% 
  mutate(SVM_Score = -SVM_Score) %>% 
  left_join(Pheno_TS2,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, `time post initiation of treatment:ch1`) %>% dplyr::rename(illness = `time post initiation of treatment:ch1`) %>% mutate(illness= case_when(illness=="0_months" ~ "TB", illness == "12_months" ~ "TB (12 mo)"))

colour_graph_TS2 <- c(rep("#636363",1), rep("#fafcfb", 1),rep("#636363",1),rep("#fafcfb", 1),rep("#636363",3),rep("#fafcfb", 3), rep("#636363", 1), rep("#fafcfb", 1),rep("#636363", 1), rep("#fafcfb", 1))

ggplot(SVM_Scores_TS2, aes(x= reorder(Sample_ID, -SVM_Score), y=SVM_Score)) + geom_col(stat = "identity", fill = colour_graph_TS2, color = "black") +  labs(title = "Test Set 2", y = "SVM Score") + theme_classic() + theme(plot.title=element_text(hjust=0.5, size=15), axis.title.x = element_text(hjust = 0.5), axis.title.y = element_text(size=15)) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank())
```




```{r svm TS3}
Pheno_TS3_illnessupdate <- Pheno_TS3 %>% dplyr::rename(illness = `illness:ch1`) %>% mutate(illness = case_when(illness == "Latent" ~ "Controls/Latent TB", illness == "Control(BCG-)" ~ "Controls/Latent TB", illness == "PTB" ~ "TB", illness== "Control (BCG+)" ~ "Controls/Latent TB"))

Expression_TS3_t <- as.data.frame(t(TS3_normalized.1))
Pheno_TS3_illness <- factor(Pheno_TS3_illnessupdate$illness)
svm_data_TS3 <- cbind(Expression_TS3_t, Pheno_TS3_illness)
svm_data_TS3_251 <- svm_data_TS3[,colnames(svm_data_TS3) %in% keep_genes] %>% cbind(Pheno_TS3_illness)

fit_TS3 = svm(Pheno_TS3_illness ~ ., data=svm_data_TS3_251, kernel="linear", cost=1)  
svm_score_TS3 <- predict(fit_TS3, svm_data_TS3_251, decision.values = TRUE)
svm_score_TS3

SVM_Scores_TS3<- read.csv("SVM_Scores_TS3.csv")%>% dplyr::rename(Sample_ID = 1) %>% mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "TB", SVM_Score>=0 ~ "Controls/Latent TB")) %>% left_join(Pheno_TS3_illnessupdate,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, illness)

```




```{r svm TS4}
Pheno_TS4_illnessupdate <- Pheno_TS4 %>% dplyr::rename(illness = characteristics_ch1.3) %>% mutate(illness = case_when(illness == "illness: Control (BCG+)" ~ "Controls/Latent TB", illness == "illness: Latent" ~ "Controls/Latent TB", illness == "illness: PTB" ~ "TB"))

Expression_TS4_t <- as.data.frame(t(TS4_normalized.1))
Pheno_TS4_illness <- factor(Pheno_TS4_illnessupdate$illness)
svm_data_TS4 <- cbind(Expression_TS4_t, Pheno_TS4_illness)
svm_data_TS4_251 <- svm_data_TS4[,colnames(svm_data_TS4) %in% keep_genes] %>% cbind(Pheno_TS4_illness) %>% dplyr::select(-ILMN_1738075)

fit_TS4 = svm(Pheno_TS4_illness ~ ., data=svm_data_TS4_251, kernel="linear", cost=1)  
svm_score_TS4 <- predict(fit_TS4, svm_data_TS4_251, decision.values = TRUE)
svm_score_TS4

SVM_Scores_TS4<- read.csv("SVM_Scores_TS4.csv")%>% dplyr::rename(Sample_ID = 1) %>% mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "Controls/Latent TB ", SVM_Score>=0 ~ "TB")) %>% left_join(Pheno_TS4_illnessupdate,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, illness)

```




```{r svm TS5}
Pheno_TS5_illnessupdate <- Pheno_TS5 %>% dplyr::rename(illness = `illness:ch1`) %>% mutate(illness = case_when(illness == "LATENT TB" ~ "Latent TB", illness == "PTB" ~ "TB"))

Expression_TS5_t <- as.data.frame(t(TS5_normalized.1))
Pheno_TS5_illness <- factor(Pheno_TS5_illnessupdate$illness)
svm_data_TS5 <- cbind(Expression_TS5_t, Pheno_TS5_illness)
svm_data_TS5_251 <- svm_data_TS5[,colnames(svm_data_TS5) %in% keep_genes] %>% cbind(Pheno_TS5_illness) %>% dplyr::select(-ILMN_1738075)

fit_TS5 = svm(Pheno_TS5_illness ~ ., data=svm_data_TS5_251, kernel="linear", cost=1)  
svm_score_TS5 <- predict(fit_TS5, svm_data_TS5_251, decision.values = TRUE)
svm_score_TS5

SVM_Scores_TS5<- read.csv("SVM_Scores_TS5.csv")%>% dplyr::rename(Sample_ID = 1) %>% mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "Latent TB", SVM_Score>=0 ~ "TB")) %>% left_join(Pheno_TS5_illnessupdate,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, illness)

```




```{r svm TS6}
Pheno_TS6_illnessupdate <- Pheno_TS6 %>% dplyr::rename(illness = characteristics_ch1) %>% mutate(illness = case_when(illness == "disease: LTB" ~ "Latent TB", illness == "disease: PTB" ~ "TB"))

Expression_TS6_t <- as.data.frame(t(TS6_normalized.1))
Pheno_TS6_illness <- factor(Pheno_TS6_illnessupdate$illness)
svm_data_TS6 <- cbind(Expression_TS6_t, Pheno_TS6_illness)
svm_data_TS6_251 <- svm_data_TS6[,colnames(svm_data_TS6) %in% keep_genes] %>% cbind(Pheno_TS6_illness) %>% dplyr::select(-ILMN_1738075,ILMN_3178258, -ILMN_3211935, -ILMN_3226904, -ILMN_3235593, -ILMN_3235642, -ILMN_3244240, -ILMN_3246608, -ILMN_3247781, -ILMN_3251217, -c(241:251), -ILMN_3178258)

fit_TS6 = svm(Pheno_TS6_illness ~ ., data=svm_data_TS6_251, kernel="linear", cost=1)  
svm_score_TS6 <- predict(fit_TS6, svm_data_TS6_251, decision.values = TRUE)
svm_score_TS6

SVM_Scores_TS6<- read.csv("SVM_Scores_TS6.csv")%>% dplyr::rename(Sample_ID = 1) %>% mutate(Predicted_Illness = case_when(SVM_Score <0 ~ "Latent TB", SVM_Score>=0 ~ "TB")) %>% left_join(Pheno_TS6_illnessupdate,by=c("Sample_ID" = "geo_accession")) %>% dplyr::select(Sample_ID, SVM_Score, Predicted_Illness, illness)

```


```{r rocplot}

#Origin
SVM_Scores_Origin_df <- SVM_Scores_Origin %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "HIV" ~ 1, illness == "HIV/TB co-infection" ~ 0))
SVM_Scores_Origin_pred <- prediction(SVM_Scores_Origin_df$predictions, SVM_Scores_Origin_df$labels)
SVM_Scores_Origin_perf <- performance(SVM_Scores_Origin_pred,"tpr","fpr")
plot(SVM_Scores_Origin_perf,col='red', main="Training Set", lwd=3)

auc_ROCR_Origin <- performance(SVM_Scores_Origin_pred, measure = "auc")
auc_ROCR_Origin <- auc_ROCR_Origin@y.values[[1]]

#TS1
SVM_Scores_TS1_df <- SVM_Scores_TS1 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "Controls" ~ 1, illness == "TB (2 mo)" ~ 0))
SVM_Scores_TS1_pred <- prediction(SVM_Scores_TS1_df$predictions, SVM_Scores_TS1_df$labels)
SVM_Scores_TS1_perf <- performance(SVM_Scores_TS1_pred,"tpr","fpr")
plot(SVM_Scores_TS1_perf,col='red', main="TS1", lwd=3)

auc_ROCR_TS1 <- performance(SVM_Scores_TS1_pred, measure = "auc")
auc_ROCR_TS1 <- auc_ROCR_TS1@y.values[[1]]

#TS2
SVM_Scores_TS2_df <- SVM_Scores_TS2 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "TB" ~ 1, illness == "TB (12 mo)" ~0))
SVM_Scores_TS2_pred <- prediction(SVM_Scores_TS2_df$predictions, SVM_Scores_TS2_df$labels)
SVM_Scores_TS2_perf <- performance(SVM_Scores_TS2_pred,"tpr","fpr")
plot(SVM_Scores_TS2_perf,col='red', main="TS2", lwd=3)

auc_ROCR_TS2 <- performance(SVM_Scores_TS2_pred, measure = "auc")
auc_ROCR_TS2 <- auc_ROCR_TS2@y.values[[1]]

#TS3
SVM_Scores_TS3_df <- SVM_Scores_TS3 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "Controls/Latent TB" ~ 1, illness == "TB" ~ 0))
SVM_Scores_TS3_pred <- prediction(SVM_Scores_TS3_df$predictions, SVM_Scores_TS3_df$labels)
SVM_Scores_TS3_perf <- performance(SVM_Scores_TS3_pred,"tpr","fpr")
plot(SVM_Scores_TS3_perf,col='red', main = "TS3", lwd=3)

auc_ROCR_TS3 <- performance(SVM_Scores_TS3_pred, measure = "auc")
auc_ROCR_TS3 <- auc_ROCR_TS3@y.values[[1]]

#TS4
SVM_Scores_TS4_df <- SVM_Scores_TS4 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "TB" ~ 1, illness == "Controls/Latent TB" ~ 0))
SVM_Scores_TS4_pred <- prediction(SVM_Scores_TS4_df$predictions, SVM_Scores_TS4_df$labels)
SVM_Scores_TS4_perf <- performance(SVM_Scores_TS4_pred,"tpr","fpr")
plot(SVM_Scores_TS4_perf,col='red', main = "TS4", lwd=3)

auc_ROCR_TS4 <- performance(SVM_Scores_TS4_pred, measure = "auc")
auc_ROCR_TS4 <- auc_ROCR_TS4@y.values[[1]]


#TS5
SVM_Scores_TS5_df <- SVM_Scores_TS5 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "TB" ~ 1, illness == "Latent TB" ~ 0))
SVM_Scores_TS5_pred <- prediction(SVM_Scores_TS5_df$predictions, SVM_Scores_TS5_df$labels)
SVM_Scores_TS5_perf <- performance(SVM_Scores_TS5_pred,"tpr","fpr")
plot(SVM_Scores_TS5_perf,col='red', main = "TS5", lwd=3)

auc_ROCR_TS5 <- performance(SVM_Scores_TS5_pred, measure = "auc")
auc_ROCR_TS5 <- auc_ROCR_TS5@y.values[[1]]


#TS6
SVM_Scores_TS6_df <- SVM_Scores_TS6 %>% mutate(predictions = case_when(SVM_Score <0 ~ 0, SVM_Score >=0 ~1)) %>% mutate(labels = case_when(illness == "TB" ~ 1, illness == "Latent TB" ~ 0))
SVM_Scores_TS6_pred <- prediction(SVM_Scores_TS6_df$predictions, SVM_Scores_TS6_df$labels)
SVM_Scores_TS6_perf <- performance(SVM_Scores_TS6_pred,"tpr","fpr")
plot(SVM_Scores_TS6_perf,col='red', main = "TS6", lwd=3)

auc_ROCR_TS6 <- performance(SVM_Scores_TS6_pred, measure = "auc")
auc_ROCR_TS6 <- auc_ROCR_TS6@y.values[[1]]

auc_ROCR_Origin
auc_ROCR_TS1
auc_ROCR_TS2
auc_ROCR_TS3
auc_ROCR_TS4
auc_ROCR_TS5
auc_ROCR_TS6
```

```{r}
confusion.glm_Origin = confusionMatrix(
  data = as.factor(SVM_Scores_Origin_df$predictions),
  reference = as.factor(SVM_Scores_Origin_df$labels)
)
confusion.glm_Origin$table
confusion.glm_Origin

confusion.glm_TS1 = confusionMatrix(
  data = as.factor(SVM_Scores_TS1_df$predictions),
  reference = as.factor(SVM_Scores_TS1_df$labels)
)
confusion.glm_TS1$table
confusion.glm_TS1


confusion.glm_TS2 = confusionMatrix(
  data = as.factor(SVM_Scores_TS2_df$predictions),
  reference = as.factor(SVM_Scores_TS2_df$labels)
)
confusion.glm_TS2$table
confusion.glm_TS2

confusion.glm_TS3 = confusionMatrix(
  data = as.factor(SVM_Scores_TS3_df$predictions),
  reference = as.factor(SVM_Scores_TS3_df$labels)
)
confusion.glm_TS3$table
confusion.glm_TS3

confusion.glm_TS4 = confusionMatrix(
  data = as.factor(SVM_Scores_TS4_df$predictions),
  reference = as.factor(SVM_Scores_TS4_df$labels)
)
confusion.glm_TS4$table
confusion.glm_TS4

confusion.glm_TS5 = confusionMatrix(
  data = as.factor(SVM_Scores_TS5_df$predictions),
  reference = as.factor(SVM_Scores_TS5_df$labels)
)
confusion.glm_TS5$table
confusion.glm_TS5


confusion.glm_TS6 = confusionMatrix(
  data = as.factor(SVM_Scores_TS6_df$predictions),
  reference = as.factor(SVM_Scores_TS6_df$labels)
)
confusion.glm_TS6$table
confusion.glm_TS6

```




